// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: conveyor/v1/service.proto

package conveyorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/conveyorq/conveyor/internal/proto/conveyor/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "conveyor.v1.TaskService"
	// WorkerServiceName is the fully-qualified name of the WorkerService service.
	WorkerServiceName = "conveyor.v1.WorkerService"
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "conveyor.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceEnqueueProcedure is the fully-qualified name of the TaskService's Enqueue RPC.
	TaskServiceEnqueueProcedure = "/conveyor.v1.TaskService/Enqueue"
	// TaskServiceEnqueueBatchProcedure is the fully-qualified name of the TaskService's EnqueueBatch
	// RPC.
	TaskServiceEnqueueBatchProcedure = "/conveyor.v1.TaskService/EnqueueBatch"
	// TaskServiceGetTaskProcedure is the fully-qualified name of the TaskService's GetTask RPC.
	TaskServiceGetTaskProcedure = "/conveyor.v1.TaskService/GetTask"
	// WorkerServiceSessionProcedure is the fully-qualified name of the WorkerService's Session RPC.
	WorkerServiceSessionProcedure = "/conveyor.v1.WorkerService/Session"
	// AdminServiceListQueuesProcedure is the fully-qualified name of the AdminService's ListQueues RPC.
	AdminServiceListQueuesProcedure = "/conveyor.v1.AdminService/ListQueues"
	// AdminServicePauseQueueProcedure is the fully-qualified name of the AdminService's PauseQueue RPC.
	AdminServicePauseQueueProcedure = "/conveyor.v1.AdminService/PauseQueue"
	// AdminServiceResumeQueueProcedure is the fully-qualified name of the AdminService's ResumeQueue
	// RPC.
	AdminServiceResumeQueueProcedure = "/conveyor.v1.AdminService/ResumeQueue"
	// AdminServiceListRateLimitsProcedure is the fully-qualified name of the AdminService's
	// ListRateLimits RPC.
	AdminServiceListRateLimitsProcedure = "/conveyor.v1.AdminService/ListRateLimits"
	// AdminServiceSetQueueRateLimitProcedure is the fully-qualified name of the AdminService's
	// SetQueueRateLimit RPC.
	AdminServiceSetQueueRateLimitProcedure = "/conveyor.v1.AdminService/SetQueueRateLimit"
	// AdminServiceDeleteQueueRateLimitProcedure is the fully-qualified name of the AdminService's
	// DeleteQueueRateLimit RPC.
	AdminServiceDeleteQueueRateLimitProcedure = "/conveyor.v1.AdminService/DeleteQueueRateLimit"
	// AdminServiceListConcurrencyLimitsProcedure is the fully-qualified name of the AdminService's
	// ListConcurrencyLimits RPC.
	AdminServiceListConcurrencyLimitsProcedure = "/conveyor.v1.AdminService/ListConcurrencyLimits"
	// AdminServiceSetQueueConcurrencyLimitProcedure is the fully-qualified name of the AdminService's
	// SetQueueConcurrencyLimit RPC.
	AdminServiceSetQueueConcurrencyLimitProcedure = "/conveyor.v1.AdminService/SetQueueConcurrencyLimit"
	// AdminServiceDeleteQueueConcurrencyLimitProcedure is the fully-qualified name of the
	// AdminService's DeleteQueueConcurrencyLimit RPC.
	AdminServiceDeleteQueueConcurrencyLimitProcedure = "/conveyor.v1.AdminService/DeleteQueueConcurrencyLimit"
	// AdminServiceListTasksProcedure is the fully-qualified name of the AdminService's ListTasks RPC.
	AdminServiceListTasksProcedure = "/conveyor.v1.AdminService/ListTasks"
	// AdminServiceCancelTaskProcedure is the fully-qualified name of the AdminService's CancelTask RPC.
	AdminServiceCancelTaskProcedure = "/conveyor.v1.AdminService/CancelTask"
	// AdminServiceDeleteTaskProcedure is the fully-qualified name of the AdminService's DeleteTask RPC.
	AdminServiceDeleteTaskProcedure = "/conveyor.v1.AdminService/DeleteTask"
	// AdminServiceRunTaskProcedure is the fully-qualified name of the AdminService's RunTask RPC.
	AdminServiceRunTaskProcedure = "/conveyor.v1.AdminService/RunTask"
	// AdminServiceArchiveTaskProcedure is the fully-qualified name of the AdminService's ArchiveTask
	// RPC.
	AdminServiceArchiveTaskProcedure = "/conveyor.v1.AdminService/ArchiveTask"
	// AdminServiceBatchDeleteTasksProcedure is the fully-qualified name of the AdminService's
	// BatchDeleteTasks RPC.
	AdminServiceBatchDeleteTasksProcedure = "/conveyor.v1.AdminService/BatchDeleteTasks"
	// AdminServiceBatchRunTasksProcedure is the fully-qualified name of the AdminService's
	// BatchRunTasks RPC.
	AdminServiceBatchRunTasksProcedure = "/conveyor.v1.AdminService/BatchRunTasks"
	// AdminServiceBatchCancelTasksProcedure is the fully-qualified name of the AdminService's
	// BatchCancelTasks RPC.
	AdminServiceBatchCancelTasksProcedure = "/conveyor.v1.AdminService/BatchCancelTasks"
	// AdminServiceBatchArchiveTasksProcedure is the fully-qualified name of the AdminService's
	// BatchArchiveTasks RPC.
	AdminServiceBatchArchiveTasksProcedure = "/conveyor.v1.AdminService/BatchArchiveTasks"
	// AdminServiceListCronProcedure is the fully-qualified name of the AdminService's ListCron RPC.
	AdminServiceListCronProcedure = "/conveyor.v1.AdminService/ListCron"
	// AdminServiceUpsertCronProcedure is the fully-qualified name of the AdminService's UpsertCron RPC.
	AdminServiceUpsertCronProcedure = "/conveyor.v1.AdminService/UpsertCron"
	// AdminServicePauseCronProcedure is the fully-qualified name of the AdminService's PauseCron RPC.
	AdminServicePauseCronProcedure = "/conveyor.v1.AdminService/PauseCron"
	// AdminServiceResumeCronProcedure is the fully-qualified name of the AdminService's ResumeCron RPC.
	AdminServiceResumeCronProcedure = "/conveyor.v1.AdminService/ResumeCron"
	// AdminServiceDeleteCronProcedure is the fully-qualified name of the AdminService's DeleteCron RPC.
	AdminServiceDeleteCronProcedure = "/conveyor.v1.AdminService/DeleteCron"
	// AdminServiceClusterInfoProcedure is the fully-qualified name of the AdminService's ClusterInfo
	// RPC.
	AdminServiceClusterInfoProcedure = "/conveyor.v1.AdminService/ClusterInfo"
	// AdminServiceListWorkerSessionsProcedure is the fully-qualified name of the AdminService's
	// ListWorkerSessions RPC.
	AdminServiceListWorkerSessionsProcedure = "/conveyor.v1.AdminService/ListWorkerSessions"
	// AdminServiceBrokerInfoProcedure is the fully-qualified name of the AdminService's BrokerInfo RPC.
	AdminServiceBrokerInfoProcedure = "/conveyor.v1.AdminService/BrokerInfo"
	// AdminServiceWatchEventsProcedure is the fully-qualified name of the AdminService's WatchEvents
	// RPC.
	AdminServiceWatchEventsProcedure = "/conveyor.v1.AdminService/WatchEvents"
)

// TaskServiceClient is a client for the conveyor.v1.TaskService service.
type TaskServiceClient interface {
	// Enqueue durably commits one task. Idempotent on a client-supplied id.
	Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error)
	// EnqueueBatch commits many tasks in one call; results are per-item.
	EnqueueBatch(context.Context, *connect.Request[v1.EnqueueBatchRequest]) (*connect.Response[v1.EnqueueBatchResponse], error)
	// GetTask returns the current state of one task.
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
}

// NewTaskServiceClient constructs a client for the conveyor.v1.TaskService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		enqueue: connect.NewClient[v1.EnqueueRequest, v1.EnqueueResponse](
			httpClient,
			baseURL+TaskServiceEnqueueProcedure,
			connect.WithSchema(taskServiceMethods.ByName("Enqueue")),
			connect.WithClientOptions(opts...),
		),
		enqueueBatch: connect.NewClient[v1.EnqueueBatchRequest, v1.EnqueueBatchResponse](
			httpClient,
			baseURL+TaskServiceEnqueueBatchProcedure,
			connect.WithSchema(taskServiceMethods.ByName("EnqueueBatch")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+TaskServiceGetTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	enqueue      *connect.Client[v1.EnqueueRequest, v1.EnqueueResponse]
	enqueueBatch *connect.Client[v1.EnqueueBatchRequest, v1.EnqueueBatchResponse]
	getTask      *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
}

// Enqueue calls conveyor.v1.TaskService.Enqueue.
func (c *taskServiceClient) Enqueue(ctx context.Context, req *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error) {
	return c.enqueue.CallUnary(ctx, req)
}

// EnqueueBatch calls conveyor.v1.TaskService.EnqueueBatch.
func (c *taskServiceClient) EnqueueBatch(ctx context.Context, req *connect.Request[v1.EnqueueBatchRequest]) (*connect.Response[v1.EnqueueBatchResponse], error) {
	return c.enqueueBatch.CallUnary(ctx, req)
}

// GetTask calls conveyor.v1.TaskService.GetTask.
func (c *taskServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the conveyor.v1.TaskService service.
type TaskServiceHandler interface {
	// Enqueue durably commits one task. Idempotent on a client-supplied id.
	Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error)
	// EnqueueBatch commits many tasks in one call; results are per-item.
	EnqueueBatch(context.Context, *connect.Request[v1.EnqueueBatchRequest]) (*connect.Response[v1.EnqueueBatchResponse], error)
	// GetTask returns the current state of one task.
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("TaskService").Methods()
	taskServiceEnqueueHandler := connect.NewUnaryHandler(
		TaskServiceEnqueueProcedure,
		svc.Enqueue,
		connect.WithSchema(taskServiceMethods.ByName("Enqueue")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceEnqueueBatchHandler := connect.NewUnaryHandler(
		TaskServiceEnqueueBatchProcedure,
		svc.EnqueueBatch,
		connect.WithSchema(taskServiceMethods.ByName("EnqueueBatch")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(taskServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/conveyor.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceEnqueueProcedure:
			taskServiceEnqueueHandler.ServeHTTP(w, r)
		case TaskServiceEnqueueBatchProcedure:
			taskServiceEnqueueBatchHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskProcedure:
			taskServiceGetTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.TaskService.Enqueue is not implemented"))
}

func (UnimplementedTaskServiceHandler) EnqueueBatch(context.Context, *connect.Request[v1.EnqueueBatchRequest]) (*connect.Response[v1.EnqueueBatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.TaskService.EnqueueBatch is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.TaskService.GetTask is not implemented"))
}

// WorkerServiceClient is a client for the conveyor.v1.WorkerService service.
type WorkerServiceClient interface {
	// Session is the single bidirectional stream a worker process holds.
	Session(context.Context) *connect.BidiStreamForClient[v1.WorkerMessage, v1.ServerMessage]
}

// NewWorkerServiceClient constructs a client for the conveyor.v1.WorkerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workerServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("WorkerService").Methods()
	return &workerServiceClient{
		session: connect.NewClient[v1.WorkerMessage, v1.ServerMessage](
			httpClient,
			baseURL+WorkerServiceSessionProcedure,
			connect.WithSchema(workerServiceMethods.ByName("Session")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workerServiceClient implements WorkerServiceClient.
type workerServiceClient struct {
	session *connect.Client[v1.WorkerMessage, v1.ServerMessage]
}

// Session calls conveyor.v1.WorkerService.Session.
func (c *workerServiceClient) Session(ctx context.Context) *connect.BidiStreamForClient[v1.WorkerMessage, v1.ServerMessage] {
	return c.session.CallBidiStream(ctx)
}

// WorkerServiceHandler is an implementation of the conveyor.v1.WorkerService service.
type WorkerServiceHandler interface {
	// Session is the single bidirectional stream a worker process holds.
	Session(context.Context, *connect.BidiStream[v1.WorkerMessage, v1.ServerMessage]) error
}

// NewWorkerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkerServiceHandler(svc WorkerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workerServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("WorkerService").Methods()
	workerServiceSessionHandler := connect.NewBidiStreamHandler(
		WorkerServiceSessionProcedure,
		svc.Session,
		connect.WithSchema(workerServiceMethods.ByName("Session")),
		connect.WithHandlerOptions(opts...),
	)
	return "/conveyor.v1.WorkerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkerServiceSessionProcedure:
			workerServiceSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkerServiceHandler struct{}

func (UnimplementedWorkerServiceHandler) Session(context.Context, *connect.BidiStream[v1.WorkerMessage, v1.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.WorkerService.Session is not implemented"))
}

// AdminServiceClient is a client for the conveyor.v1.AdminService service.
type AdminServiceClient interface {
	ListQueues(context.Context, *connect.Request[v1.ListQueuesRequest]) (*connect.Response[v1.ListQueuesResponse], error)
	PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error)
	// ListRateLimits returns every per-queue dispatch-rate override.
	ListRateLimits(context.Context, *connect.Request[v1.ListRateLimitsRequest]) (*connect.Response[v1.ListRateLimitsResponse], error)
	// SetQueueRateLimit sets a queue's dispatch-rate override.
	SetQueueRateLimit(context.Context, *connect.Request[v1.SetQueueRateLimitRequest]) (*connect.Response[v1.SetQueueRateLimitResponse], error)
	// DeleteQueueRateLimit clears a queue's override, reverting it to the default.
	DeleteQueueRateLimit(context.Context, *connect.Request[v1.DeleteQueueRateLimitRequest]) (*connect.Response[v1.DeleteQueueRateLimitResponse], error)
	// ListConcurrencyLimits returns every per-queue concurrency limit.
	ListConcurrencyLimits(context.Context, *connect.Request[v1.ListConcurrencyLimitsRequest]) (*connect.Response[v1.ListConcurrencyLimitsResponse], error)
	// SetQueueConcurrencyLimit sets a queue's per-key concurrency limit.
	SetQueueConcurrencyLimit(context.Context, *connect.Request[v1.SetQueueConcurrencyLimitRequest]) (*connect.Response[v1.SetQueueConcurrencyLimitResponse], error)
	// DeleteQueueConcurrencyLimit clears a queue's concurrency limit, leaving its keys unbounded.
	DeleteQueueConcurrencyLimit(context.Context, *connect.Request[v1.DeleteQueueConcurrencyLimitRequest]) (*connect.Response[v1.DeleteQueueConcurrencyLimitResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error)
	// ArchiveTask dead-letters a waiting (scheduled, pending, or retry) task.
	ArchiveTask(context.Context, *connect.Request[v1.ArchiveTaskRequest]) (*connect.Response[v1.ArchiveTaskResponse], error)
	// BatchDeleteTasks deletes each listed task, reporting per-id outcomes.
	BatchDeleteTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchRunTasks makes each listed task due immediately.
	BatchRunTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchCancelTasks cancels each listed task.
	BatchCancelTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchArchiveTasks dead-letters each listed task.
	BatchArchiveTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	ListCron(context.Context, *connect.Request[v1.ListCronRequest]) (*connect.Response[v1.ListCronResponse], error)
	UpsertCron(context.Context, *connect.Request[v1.UpsertCronRequest]) (*connect.Response[v1.UpsertCronResponse], error)
	PauseCron(context.Context, *connect.Request[v1.PauseCronRequest]) (*connect.Response[v1.PauseCronResponse], error)
	ResumeCron(context.Context, *connect.Request[v1.ResumeCronRequest]) (*connect.Response[v1.ResumeCronResponse], error)
	DeleteCron(context.Context, *connect.Request[v1.DeleteCronRequest]) (*connect.Response[v1.DeleteCronResponse], error)
	ClusterInfo(context.Context, *connect.Request[v1.ClusterInfoRequest]) (*connect.Response[v1.ClusterInfoResponse], error)
	// ListWorkerSessions lists the worker sessions connected to the node serving
	// the request, for the operations dashboard's worker-topology view.
	ListWorkerSessions(context.Context, *connect.Request[v1.ListWorkerSessionsRequest]) (*connect.Response[v1.ListWorkerSessionsResponse], error)
	// BrokerInfo reports the storage engine's driver and runtime statistics,
	// the analogue of a backing-store health page.
	BrokerInfo(context.Context, *connect.Request[v1.BrokerInfoRequest]) (*connect.Response[v1.BrokerInfoResponse], error)
	// WatchEvents streams task lifecycle transitions as they occur, replacing
	// polling for live dashboards, alerting, audit logs, and event-driven
	// chaining. Delivery is best-effort and non-durable: a watcher receives
	// events from the moment it subscribes, and a watcher too slow to keep up
	// has events dropped rather than stalling task processing. The optional
	// queue and event-type filters narrow the stream server-side.
	WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error)
}

// NewAdminServiceClient constructs a client for the conveyor.v1.AdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		listQueues: connect.NewClient[v1.ListQueuesRequest, v1.ListQueuesResponse](
			httpClient,
			baseURL+AdminServiceListQueuesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListQueues")),
			connect.WithClientOptions(opts...),
		),
		pauseQueue: connect.NewClient[v1.PauseQueueRequest, v1.PauseQueueResponse](
			httpClient,
			baseURL+AdminServicePauseQueueProcedure,
			connect.WithSchema(adminServiceMethods.ByName("PauseQueue")),
			connect.WithClientOptions(opts...),
		),
		resumeQueue: connect.NewClient[v1.ResumeQueueRequest, v1.ResumeQueueResponse](
			httpClient,
			baseURL+AdminServiceResumeQueueProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ResumeQueue")),
			connect.WithClientOptions(opts...),
		),
		listRateLimits: connect.NewClient[v1.ListRateLimitsRequest, v1.ListRateLimitsResponse](
			httpClient,
			baseURL+AdminServiceListRateLimitsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListRateLimits")),
			connect.WithClientOptions(opts...),
		),
		setQueueRateLimit: connect.NewClient[v1.SetQueueRateLimitRequest, v1.SetQueueRateLimitResponse](
			httpClient,
			baseURL+AdminServiceSetQueueRateLimitProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SetQueueRateLimit")),
			connect.WithClientOptions(opts...),
		),
		deleteQueueRateLimit: connect.NewClient[v1.DeleteQueueRateLimitRequest, v1.DeleteQueueRateLimitResponse](
			httpClient,
			baseURL+AdminServiceDeleteQueueRateLimitProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteQueueRateLimit")),
			connect.WithClientOptions(opts...),
		),
		listConcurrencyLimits: connect.NewClient[v1.ListConcurrencyLimitsRequest, v1.ListConcurrencyLimitsResponse](
			httpClient,
			baseURL+AdminServiceListConcurrencyLimitsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListConcurrencyLimits")),
			connect.WithClientOptions(opts...),
		),
		setQueueConcurrencyLimit: connect.NewClient[v1.SetQueueConcurrencyLimitRequest, v1.SetQueueConcurrencyLimitResponse](
			httpClient,
			baseURL+AdminServiceSetQueueConcurrencyLimitProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SetQueueConcurrencyLimit")),
			connect.WithClientOptions(opts...),
		),
		deleteQueueConcurrencyLimit: connect.NewClient[v1.DeleteQueueConcurrencyLimitRequest, v1.DeleteQueueConcurrencyLimitResponse](
			httpClient,
			baseURL+AdminServiceDeleteQueueConcurrencyLimitProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteQueueConcurrencyLimit")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+AdminServiceListTasksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		cancelTask: connect.NewClient[v1.CancelTaskRequest, v1.CancelTaskResponse](
			httpClient,
			baseURL+AdminServiceCancelTaskProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CancelTask")),
			connect.WithClientOptions(opts...),
		),
		deleteTask: connect.NewClient[v1.DeleteTaskRequest, v1.DeleteTaskResponse](
			httpClient,
			baseURL+AdminServiceDeleteTaskProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteTask")),
			connect.WithClientOptions(opts...),
		),
		runTask: connect.NewClient[v1.RunTaskRequest, v1.RunTaskResponse](
			httpClient,
			baseURL+AdminServiceRunTaskProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RunTask")),
			connect.WithClientOptions(opts...),
		),
		archiveTask: connect.NewClient[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse](
			httpClient,
			baseURL+AdminServiceArchiveTaskProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ArchiveTask")),
			connect.WithClientOptions(opts...),
		),
		batchDeleteTasks: connect.NewClient[v1.BatchTasksRequest, v1.BatchTasksResponse](
			httpClient,
			baseURL+AdminServiceBatchDeleteTasksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BatchDeleteTasks")),
			connect.WithClientOptions(opts...),
		),
		batchRunTasks: connect.NewClient[v1.BatchTasksRequest, v1.BatchTasksResponse](
			httpClient,
			baseURL+AdminServiceBatchRunTasksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BatchRunTasks")),
			connect.WithClientOptions(opts...),
		),
		batchCancelTasks: connect.NewClient[v1.BatchTasksRequest, v1.BatchTasksResponse](
			httpClient,
			baseURL+AdminServiceBatchCancelTasksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BatchCancelTasks")),
			connect.WithClientOptions(opts...),
		),
		batchArchiveTasks: connect.NewClient[v1.BatchTasksRequest, v1.BatchTasksResponse](
			httpClient,
			baseURL+AdminServiceBatchArchiveTasksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BatchArchiveTasks")),
			connect.WithClientOptions(opts...),
		),
		listCron: connect.NewClient[v1.ListCronRequest, v1.ListCronResponse](
			httpClient,
			baseURL+AdminServiceListCronProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListCron")),
			connect.WithClientOptions(opts...),
		),
		upsertCron: connect.NewClient[v1.UpsertCronRequest, v1.UpsertCronResponse](
			httpClient,
			baseURL+AdminServiceUpsertCronProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpsertCron")),
			connect.WithClientOptions(opts...),
		),
		pauseCron: connect.NewClient[v1.PauseCronRequest, v1.PauseCronResponse](
			httpClient,
			baseURL+AdminServicePauseCronProcedure,
			connect.WithSchema(adminServiceMethods.ByName("PauseCron")),
			connect.WithClientOptions(opts...),
		),
		resumeCron: connect.NewClient[v1.ResumeCronRequest, v1.ResumeCronResponse](
			httpClient,
			baseURL+AdminServiceResumeCronProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ResumeCron")),
			connect.WithClientOptions(opts...),
		),
		deleteCron: connect.NewClient[v1.DeleteCronRequest, v1.DeleteCronResponse](
			httpClient,
			baseURL+AdminServiceDeleteCronProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteCron")),
			connect.WithClientOptions(opts...),
		),
		clusterInfo: connect.NewClient[v1.ClusterInfoRequest, v1.ClusterInfoResponse](
			httpClient,
			baseURL+AdminServiceClusterInfoProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ClusterInfo")),
			connect.WithClientOptions(opts...),
		),
		listWorkerSessions: connect.NewClient[v1.ListWorkerSessionsRequest, v1.ListWorkerSessionsResponse](
			httpClient,
			baseURL+AdminServiceListWorkerSessionsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListWorkerSessions")),
			connect.WithClientOptions(opts...),
		),
		brokerInfo: connect.NewClient[v1.BrokerInfoRequest, v1.BrokerInfoResponse](
			httpClient,
			baseURL+AdminServiceBrokerInfoProcedure,
			connect.WithSchema(adminServiceMethods.ByName("BrokerInfo")),
			connect.WithClientOptions(opts...),
		),
		watchEvents: connect.NewClient[v1.WatchEventsRequest, v1.TaskEvent](
			httpClient,
			baseURL+AdminServiceWatchEventsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("WatchEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	listQueues                  *connect.Client[v1.ListQueuesRequest, v1.ListQueuesResponse]
	pauseQueue                  *connect.Client[v1.PauseQueueRequest, v1.PauseQueueResponse]
	resumeQueue                 *connect.Client[v1.ResumeQueueRequest, v1.ResumeQueueResponse]
	listRateLimits              *connect.Client[v1.ListRateLimitsRequest, v1.ListRateLimitsResponse]
	setQueueRateLimit           *connect.Client[v1.SetQueueRateLimitRequest, v1.SetQueueRateLimitResponse]
	deleteQueueRateLimit        *connect.Client[v1.DeleteQueueRateLimitRequest, v1.DeleteQueueRateLimitResponse]
	listConcurrencyLimits       *connect.Client[v1.ListConcurrencyLimitsRequest, v1.ListConcurrencyLimitsResponse]
	setQueueConcurrencyLimit    *connect.Client[v1.SetQueueConcurrencyLimitRequest, v1.SetQueueConcurrencyLimitResponse]
	deleteQueueConcurrencyLimit *connect.Client[v1.DeleteQueueConcurrencyLimitRequest, v1.DeleteQueueConcurrencyLimitResponse]
	listTasks                   *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	cancelTask                  *connect.Client[v1.CancelTaskRequest, v1.CancelTaskResponse]
	deleteTask                  *connect.Client[v1.DeleteTaskRequest, v1.DeleteTaskResponse]
	runTask                     *connect.Client[v1.RunTaskRequest, v1.RunTaskResponse]
	archiveTask                 *connect.Client[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse]
	batchDeleteTasks            *connect.Client[v1.BatchTasksRequest, v1.BatchTasksResponse]
	batchRunTasks               *connect.Client[v1.BatchTasksRequest, v1.BatchTasksResponse]
	batchCancelTasks            *connect.Client[v1.BatchTasksRequest, v1.BatchTasksResponse]
	batchArchiveTasks           *connect.Client[v1.BatchTasksRequest, v1.BatchTasksResponse]
	listCron                    *connect.Client[v1.ListCronRequest, v1.ListCronResponse]
	upsertCron                  *connect.Client[v1.UpsertCronRequest, v1.UpsertCronResponse]
	pauseCron                   *connect.Client[v1.PauseCronRequest, v1.PauseCronResponse]
	resumeCron                  *connect.Client[v1.ResumeCronRequest, v1.ResumeCronResponse]
	deleteCron                  *connect.Client[v1.DeleteCronRequest, v1.DeleteCronResponse]
	clusterInfo                 *connect.Client[v1.ClusterInfoRequest, v1.ClusterInfoResponse]
	listWorkerSessions          *connect.Client[v1.ListWorkerSessionsRequest, v1.ListWorkerSessionsResponse]
	brokerInfo                  *connect.Client[v1.BrokerInfoRequest, v1.BrokerInfoResponse]
	watchEvents                 *connect.Client[v1.WatchEventsRequest, v1.TaskEvent]
}

// ListQueues calls conveyor.v1.AdminService.ListQueues.
func (c *adminServiceClient) ListQueues(ctx context.Context, req *connect.Request[v1.ListQueuesRequest]) (*connect.Response[v1.ListQueuesResponse], error) {
	return c.listQueues.CallUnary(ctx, req)
}

// PauseQueue calls conveyor.v1.AdminService.PauseQueue.
func (c *adminServiceClient) PauseQueue(ctx context.Context, req *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error) {
	return c.pauseQueue.CallUnary(ctx, req)
}

// ResumeQueue calls conveyor.v1.AdminService.ResumeQueue.
func (c *adminServiceClient) ResumeQueue(ctx context.Context, req *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error) {
	return c.resumeQueue.CallUnary(ctx, req)
}

// ListRateLimits calls conveyor.v1.AdminService.ListRateLimits.
func (c *adminServiceClient) ListRateLimits(ctx context.Context, req *connect.Request[v1.ListRateLimitsRequest]) (*connect.Response[v1.ListRateLimitsResponse], error) {
	return c.listRateLimits.CallUnary(ctx, req)
}

// SetQueueRateLimit calls conveyor.v1.AdminService.SetQueueRateLimit.
func (c *adminServiceClient) SetQueueRateLimit(ctx context.Context, req *connect.Request[v1.SetQueueRateLimitRequest]) (*connect.Response[v1.SetQueueRateLimitResponse], error) {
	return c.setQueueRateLimit.CallUnary(ctx, req)
}

// DeleteQueueRateLimit calls conveyor.v1.AdminService.DeleteQueueRateLimit.
func (c *adminServiceClient) DeleteQueueRateLimit(ctx context.Context, req *connect.Request[v1.DeleteQueueRateLimitRequest]) (*connect.Response[v1.DeleteQueueRateLimitResponse], error) {
	return c.deleteQueueRateLimit.CallUnary(ctx, req)
}

// ListConcurrencyLimits calls conveyor.v1.AdminService.ListConcurrencyLimits.
func (c *adminServiceClient) ListConcurrencyLimits(ctx context.Context, req *connect.Request[v1.ListConcurrencyLimitsRequest]) (*connect.Response[v1.ListConcurrencyLimitsResponse], error) {
	return c.listConcurrencyLimits.CallUnary(ctx, req)
}

// SetQueueConcurrencyLimit calls conveyor.v1.AdminService.SetQueueConcurrencyLimit.
func (c *adminServiceClient) SetQueueConcurrencyLimit(ctx context.Context, req *connect.Request[v1.SetQueueConcurrencyLimitRequest]) (*connect.Response[v1.SetQueueConcurrencyLimitResponse], error) {
	return c.setQueueConcurrencyLimit.CallUnary(ctx, req)
}

// DeleteQueueConcurrencyLimit calls conveyor.v1.AdminService.DeleteQueueConcurrencyLimit.
func (c *adminServiceClient) DeleteQueueConcurrencyLimit(ctx context.Context, req *connect.Request[v1.DeleteQueueConcurrencyLimitRequest]) (*connect.Response[v1.DeleteQueueConcurrencyLimitResponse], error) {
	return c.deleteQueueConcurrencyLimit.CallUnary(ctx, req)
}

// ListTasks calls conveyor.v1.AdminService.ListTasks.
func (c *adminServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// CancelTask calls conveyor.v1.AdminService.CancelTask.
func (c *adminServiceClient) CancelTask(ctx context.Context, req *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return c.cancelTask.CallUnary(ctx, req)
}

// DeleteTask calls conveyor.v1.AdminService.DeleteTask.
func (c *adminServiceClient) DeleteTask(ctx context.Context, req *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return c.deleteTask.CallUnary(ctx, req)
}

// RunTask calls conveyor.v1.AdminService.RunTask.
func (c *adminServiceClient) RunTask(ctx context.Context, req *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error) {
	return c.runTask.CallUnary(ctx, req)
}

// ArchiveTask calls conveyor.v1.AdminService.ArchiveTask.
func (c *adminServiceClient) ArchiveTask(ctx context.Context, req *connect.Request[v1.ArchiveTaskRequest]) (*connect.Response[v1.ArchiveTaskResponse], error) {
	return c.archiveTask.CallUnary(ctx, req)
}

// BatchDeleteTasks calls conveyor.v1.AdminService.BatchDeleteTasks.
func (c *adminServiceClient) BatchDeleteTasks(ctx context.Context, req *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return c.batchDeleteTasks.CallUnary(ctx, req)
}

// BatchRunTasks calls conveyor.v1.AdminService.BatchRunTasks.
func (c *adminServiceClient) BatchRunTasks(ctx context.Context, req *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return c.batchRunTasks.CallUnary(ctx, req)
}

// BatchCancelTasks calls conveyor.v1.AdminService.BatchCancelTasks.
func (c *adminServiceClient) BatchCancelTasks(ctx context.Context, req *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return c.batchCancelTasks.CallUnary(ctx, req)
}

// BatchArchiveTasks calls conveyor.v1.AdminService.BatchArchiveTasks.
func (c *adminServiceClient) BatchArchiveTasks(ctx context.Context, req *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return c.batchArchiveTasks.CallUnary(ctx, req)
}

// ListCron calls conveyor.v1.AdminService.ListCron.
func (c *adminServiceClient) ListCron(ctx context.Context, req *connect.Request[v1.ListCronRequest]) (*connect.Response[v1.ListCronResponse], error) {
	return c.listCron.CallUnary(ctx, req)
}

// UpsertCron calls conveyor.v1.AdminService.UpsertCron.
func (c *adminServiceClient) UpsertCron(ctx context.Context, req *connect.Request[v1.UpsertCronRequest]) (*connect.Response[v1.UpsertCronResponse], error) {
	return c.upsertCron.CallUnary(ctx, req)
}

// PauseCron calls conveyor.v1.AdminService.PauseCron.
func (c *adminServiceClient) PauseCron(ctx context.Context, req *connect.Request[v1.PauseCronRequest]) (*connect.Response[v1.PauseCronResponse], error) {
	return c.pauseCron.CallUnary(ctx, req)
}

// ResumeCron calls conveyor.v1.AdminService.ResumeCron.
func (c *adminServiceClient) ResumeCron(ctx context.Context, req *connect.Request[v1.ResumeCronRequest]) (*connect.Response[v1.ResumeCronResponse], error) {
	return c.resumeCron.CallUnary(ctx, req)
}

// DeleteCron calls conveyor.v1.AdminService.DeleteCron.
func (c *adminServiceClient) DeleteCron(ctx context.Context, req *connect.Request[v1.DeleteCronRequest]) (*connect.Response[v1.DeleteCronResponse], error) {
	return c.deleteCron.CallUnary(ctx, req)
}

// ClusterInfo calls conveyor.v1.AdminService.ClusterInfo.
func (c *adminServiceClient) ClusterInfo(ctx context.Context, req *connect.Request[v1.ClusterInfoRequest]) (*connect.Response[v1.ClusterInfoResponse], error) {
	return c.clusterInfo.CallUnary(ctx, req)
}

// ListWorkerSessions calls conveyor.v1.AdminService.ListWorkerSessions.
func (c *adminServiceClient) ListWorkerSessions(ctx context.Context, req *connect.Request[v1.ListWorkerSessionsRequest]) (*connect.Response[v1.ListWorkerSessionsResponse], error) {
	return c.listWorkerSessions.CallUnary(ctx, req)
}

// BrokerInfo calls conveyor.v1.AdminService.BrokerInfo.
func (c *adminServiceClient) BrokerInfo(ctx context.Context, req *connect.Request[v1.BrokerInfoRequest]) (*connect.Response[v1.BrokerInfoResponse], error) {
	return c.brokerInfo.CallUnary(ctx, req)
}

// WatchEvents calls conveyor.v1.AdminService.WatchEvents.
func (c *adminServiceClient) WatchEvents(ctx context.Context, req *connect.Request[v1.WatchEventsRequest]) (*connect.ServerStreamForClient[v1.TaskEvent], error) {
	return c.watchEvents.CallServerStream(ctx, req)
}

// AdminServiceHandler is an implementation of the conveyor.v1.AdminService service.
type AdminServiceHandler interface {
	ListQueues(context.Context, *connect.Request[v1.ListQueuesRequest]) (*connect.Response[v1.ListQueuesResponse], error)
	PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error)
	// ListRateLimits returns every per-queue dispatch-rate override.
	ListRateLimits(context.Context, *connect.Request[v1.ListRateLimitsRequest]) (*connect.Response[v1.ListRateLimitsResponse], error)
	// SetQueueRateLimit sets a queue's dispatch-rate override.
	SetQueueRateLimit(context.Context, *connect.Request[v1.SetQueueRateLimitRequest]) (*connect.Response[v1.SetQueueRateLimitResponse], error)
	// DeleteQueueRateLimit clears a queue's override, reverting it to the default.
	DeleteQueueRateLimit(context.Context, *connect.Request[v1.DeleteQueueRateLimitRequest]) (*connect.Response[v1.DeleteQueueRateLimitResponse], error)
	// ListConcurrencyLimits returns every per-queue concurrency limit.
	ListConcurrencyLimits(context.Context, *connect.Request[v1.ListConcurrencyLimitsRequest]) (*connect.Response[v1.ListConcurrencyLimitsResponse], error)
	// SetQueueConcurrencyLimit sets a queue's per-key concurrency limit.
	SetQueueConcurrencyLimit(context.Context, *connect.Request[v1.SetQueueConcurrencyLimitRequest]) (*connect.Response[v1.SetQueueConcurrencyLimitResponse], error)
	// DeleteQueueConcurrencyLimit clears a queue's concurrency limit, leaving its keys unbounded.
	DeleteQueueConcurrencyLimit(context.Context, *connect.Request[v1.DeleteQueueConcurrencyLimitRequest]) (*connect.Response[v1.DeleteQueueConcurrencyLimitResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error)
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error)
	// ArchiveTask dead-letters a waiting (scheduled, pending, or retry) task.
	ArchiveTask(context.Context, *connect.Request[v1.ArchiveTaskRequest]) (*connect.Response[v1.ArchiveTaskResponse], error)
	// BatchDeleteTasks deletes each listed task, reporting per-id outcomes.
	BatchDeleteTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchRunTasks makes each listed task due immediately.
	BatchRunTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchCancelTasks cancels each listed task.
	BatchCancelTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	// BatchArchiveTasks dead-letters each listed task.
	BatchArchiveTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error)
	ListCron(context.Context, *connect.Request[v1.ListCronRequest]) (*connect.Response[v1.ListCronResponse], error)
	UpsertCron(context.Context, *connect.Request[v1.UpsertCronRequest]) (*connect.Response[v1.UpsertCronResponse], error)
	PauseCron(context.Context, *connect.Request[v1.PauseCronRequest]) (*connect.Response[v1.PauseCronResponse], error)
	ResumeCron(context.Context, *connect.Request[v1.ResumeCronRequest]) (*connect.Response[v1.ResumeCronResponse], error)
	DeleteCron(context.Context, *connect.Request[v1.DeleteCronRequest]) (*connect.Response[v1.DeleteCronResponse], error)
	ClusterInfo(context.Context, *connect.Request[v1.ClusterInfoRequest]) (*connect.Response[v1.ClusterInfoResponse], error)
	// ListWorkerSessions lists the worker sessions connected to the node serving
	// the request, for the operations dashboard's worker-topology view.
	ListWorkerSessions(context.Context, *connect.Request[v1.ListWorkerSessionsRequest]) (*connect.Response[v1.ListWorkerSessionsResponse], error)
	// BrokerInfo reports the storage engine's driver and runtime statistics,
	// the analogue of a backing-store health page.
	BrokerInfo(context.Context, *connect.Request[v1.BrokerInfoRequest]) (*connect.Response[v1.BrokerInfoResponse], error)
	// WatchEvents streams task lifecycle transitions as they occur, replacing
	// polling for live dashboards, alerting, audit logs, and event-driven
	// chaining. Delivery is best-effort and non-durable: a watcher receives
	// events from the moment it subscribes, and a watcher too slow to keep up
	// has events dropped rather than stalling task processing. The optional
	// queue and event-type filters narrow the stream server-side.
	WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest], *connect.ServerStream[v1.TaskEvent]) error
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_conveyor_v1_service_proto.Services().ByName("AdminService").Methods()
	adminServiceListQueuesHandler := connect.NewUnaryHandler(
		AdminServiceListQueuesProcedure,
		svc.ListQueues,
		connect.WithSchema(adminServiceMethods.ByName("ListQueues")),
		connect.WithHandlerOptions(opts...),
	)
	adminServicePauseQueueHandler := connect.NewUnaryHandler(
		AdminServicePauseQueueProcedure,
		svc.PauseQueue,
		connect.WithSchema(adminServiceMethods.ByName("PauseQueue")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceResumeQueueHandler := connect.NewUnaryHandler(
		AdminServiceResumeQueueProcedure,
		svc.ResumeQueue,
		connect.WithSchema(adminServiceMethods.ByName("ResumeQueue")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListRateLimitsHandler := connect.NewUnaryHandler(
		AdminServiceListRateLimitsProcedure,
		svc.ListRateLimits,
		connect.WithSchema(adminServiceMethods.ByName("ListRateLimits")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSetQueueRateLimitHandler := connect.NewUnaryHandler(
		AdminServiceSetQueueRateLimitProcedure,
		svc.SetQueueRateLimit,
		connect.WithSchema(adminServiceMethods.ByName("SetQueueRateLimit")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteQueueRateLimitHandler := connect.NewUnaryHandler(
		AdminServiceDeleteQueueRateLimitProcedure,
		svc.DeleteQueueRateLimit,
		connect.WithSchema(adminServiceMethods.ByName("DeleteQueueRateLimit")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListConcurrencyLimitsHandler := connect.NewUnaryHandler(
		AdminServiceListConcurrencyLimitsProcedure,
		svc.ListConcurrencyLimits,
		connect.WithSchema(adminServiceMethods.ByName("ListConcurrencyLimits")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSetQueueConcurrencyLimitHandler := connect.NewUnaryHandler(
		AdminServiceSetQueueConcurrencyLimitProcedure,
		svc.SetQueueConcurrencyLimit,
		connect.WithSchema(adminServiceMethods.ByName("SetQueueConcurrencyLimit")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteQueueConcurrencyLimitHandler := connect.NewUnaryHandler(
		AdminServiceDeleteQueueConcurrencyLimitProcedure,
		svc.DeleteQueueConcurrencyLimit,
		connect.WithSchema(adminServiceMethods.ByName("DeleteQueueConcurrencyLimit")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListTasksHandler := connect.NewUnaryHandler(
		AdminServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(adminServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCancelTaskHandler := connect.NewUnaryHandler(
		AdminServiceCancelTaskProcedure,
		svc.CancelTask,
		connect.WithSchema(adminServiceMethods.ByName("CancelTask")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteTaskHandler := connect.NewUnaryHandler(
		AdminServiceDeleteTaskProcedure,
		svc.DeleteTask,
		connect.WithSchema(adminServiceMethods.ByName("DeleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRunTaskHandler := connect.NewUnaryHandler(
		AdminServiceRunTaskProcedure,
		svc.RunTask,
		connect.WithSchema(adminServiceMethods.ByName("RunTask")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceArchiveTaskHandler := connect.NewUnaryHandler(
		AdminServiceArchiveTaskProcedure,
		svc.ArchiveTask,
		connect.WithSchema(adminServiceMethods.ByName("ArchiveTask")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBatchDeleteTasksHandler := connect.NewUnaryHandler(
		AdminServiceBatchDeleteTasksProcedure,
		svc.BatchDeleteTasks,
		connect.WithSchema(adminServiceMethods.ByName("BatchDeleteTasks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBatchRunTasksHandler := connect.NewUnaryHandler(
		AdminServiceBatchRunTasksProcedure,
		svc.BatchRunTasks,
		connect.WithSchema(adminServiceMethods.ByName("BatchRunTasks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBatchCancelTasksHandler := connect.NewUnaryHandler(
		AdminServiceBatchCancelTasksProcedure,
		svc.BatchCancelTasks,
		connect.WithSchema(adminServiceMethods.ByName("BatchCancelTasks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBatchArchiveTasksHandler := connect.NewUnaryHandler(
		AdminServiceBatchArchiveTasksProcedure,
		svc.BatchArchiveTasks,
		connect.WithSchema(adminServiceMethods.ByName("BatchArchiveTasks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListCronHandler := connect.NewUnaryHandler(
		AdminServiceListCronProcedure,
		svc.ListCron,
		connect.WithSchema(adminServiceMethods.ByName("ListCron")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpsertCronHandler := connect.NewUnaryHandler(
		AdminServiceUpsertCronProcedure,
		svc.UpsertCron,
		connect.WithSchema(adminServiceMethods.ByName("UpsertCron")),
		connect.WithHandlerOptions(opts...),
	)
	adminServicePauseCronHandler := connect.NewUnaryHandler(
		AdminServicePauseCronProcedure,
		svc.PauseCron,
		connect.WithSchema(adminServiceMethods.ByName("PauseCron")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceResumeCronHandler := connect.NewUnaryHandler(
		AdminServiceResumeCronProcedure,
		svc.ResumeCron,
		connect.WithSchema(adminServiceMethods.ByName("ResumeCron")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteCronHandler := connect.NewUnaryHandler(
		AdminServiceDeleteCronProcedure,
		svc.DeleteCron,
		connect.WithSchema(adminServiceMethods.ByName("DeleteCron")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceClusterInfoHandler := connect.NewUnaryHandler(
		AdminServiceClusterInfoProcedure,
		svc.ClusterInfo,
		connect.WithSchema(adminServiceMethods.ByName("ClusterInfo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListWorkerSessionsHandler := connect.NewUnaryHandler(
		AdminServiceListWorkerSessionsProcedure,
		svc.ListWorkerSessions,
		connect.WithSchema(adminServiceMethods.ByName("ListWorkerSessions")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceBrokerInfoHandler := connect.NewUnaryHandler(
		AdminServiceBrokerInfoProcedure,
		svc.BrokerInfo,
		connect.WithSchema(adminServiceMethods.ByName("BrokerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceWatchEventsHandler := connect.NewServerStreamHandler(
		AdminServiceWatchEventsProcedure,
		svc.WatchEvents,
		connect.WithSchema(adminServiceMethods.ByName("WatchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/conveyor.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceListQueuesProcedure:
			adminServiceListQueuesHandler.ServeHTTP(w, r)
		case AdminServicePauseQueueProcedure:
			adminServicePauseQueueHandler.ServeHTTP(w, r)
		case AdminServiceResumeQueueProcedure:
			adminServiceResumeQueueHandler.ServeHTTP(w, r)
		case AdminServiceListRateLimitsProcedure:
			adminServiceListRateLimitsHandler.ServeHTTP(w, r)
		case AdminServiceSetQueueRateLimitProcedure:
			adminServiceSetQueueRateLimitHandler.ServeHTTP(w, r)
		case AdminServiceDeleteQueueRateLimitProcedure:
			adminServiceDeleteQueueRateLimitHandler.ServeHTTP(w, r)
		case AdminServiceListConcurrencyLimitsProcedure:
			adminServiceListConcurrencyLimitsHandler.ServeHTTP(w, r)
		case AdminServiceSetQueueConcurrencyLimitProcedure:
			adminServiceSetQueueConcurrencyLimitHandler.ServeHTTP(w, r)
		case AdminServiceDeleteQueueConcurrencyLimitProcedure:
			adminServiceDeleteQueueConcurrencyLimitHandler.ServeHTTP(w, r)
		case AdminServiceListTasksProcedure:
			adminServiceListTasksHandler.ServeHTTP(w, r)
		case AdminServiceCancelTaskProcedure:
			adminServiceCancelTaskHandler.ServeHTTP(w, r)
		case AdminServiceDeleteTaskProcedure:
			adminServiceDeleteTaskHandler.ServeHTTP(w, r)
		case AdminServiceRunTaskProcedure:
			adminServiceRunTaskHandler.ServeHTTP(w, r)
		case AdminServiceArchiveTaskProcedure:
			adminServiceArchiveTaskHandler.ServeHTTP(w, r)
		case AdminServiceBatchDeleteTasksProcedure:
			adminServiceBatchDeleteTasksHandler.ServeHTTP(w, r)
		case AdminServiceBatchRunTasksProcedure:
			adminServiceBatchRunTasksHandler.ServeHTTP(w, r)
		case AdminServiceBatchCancelTasksProcedure:
			adminServiceBatchCancelTasksHandler.ServeHTTP(w, r)
		case AdminServiceBatchArchiveTasksProcedure:
			adminServiceBatchArchiveTasksHandler.ServeHTTP(w, r)
		case AdminServiceListCronProcedure:
			adminServiceListCronHandler.ServeHTTP(w, r)
		case AdminServiceUpsertCronProcedure:
			adminServiceUpsertCronHandler.ServeHTTP(w, r)
		case AdminServicePauseCronProcedure:
			adminServicePauseCronHandler.ServeHTTP(w, r)
		case AdminServiceResumeCronProcedure:
			adminServiceResumeCronHandler.ServeHTTP(w, r)
		case AdminServiceDeleteCronProcedure:
			adminServiceDeleteCronHandler.ServeHTTP(w, r)
		case AdminServiceClusterInfoProcedure:
			adminServiceClusterInfoHandler.ServeHTTP(w, r)
		case AdminServiceListWorkerSessionsProcedure:
			adminServiceListWorkerSessionsHandler.ServeHTTP(w, r)
		case AdminServiceBrokerInfoProcedure:
			adminServiceBrokerInfoHandler.ServeHTTP(w, r)
		case AdminServiceWatchEventsProcedure:
			adminServiceWatchEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) ListQueues(context.Context, *connect.Request[v1.ListQueuesRequest]) (*connect.Response[v1.ListQueuesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListQueues is not implemented"))
}

func (UnimplementedAdminServiceHandler) PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.PauseQueue is not implemented"))
}

func (UnimplementedAdminServiceHandler) ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ResumeQueue is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListRateLimits(context.Context, *connect.Request[v1.ListRateLimitsRequest]) (*connect.Response[v1.ListRateLimitsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListRateLimits is not implemented"))
}

func (UnimplementedAdminServiceHandler) SetQueueRateLimit(context.Context, *connect.Request[v1.SetQueueRateLimitRequest]) (*connect.Response[v1.SetQueueRateLimitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.SetQueueRateLimit is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteQueueRateLimit(context.Context, *connect.Request[v1.DeleteQueueRateLimitRequest]) (*connect.Response[v1.DeleteQueueRateLimitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.DeleteQueueRateLimit is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListConcurrencyLimits(context.Context, *connect.Request[v1.ListConcurrencyLimitsRequest]) (*connect.Response[v1.ListConcurrencyLimitsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListConcurrencyLimits is not implemented"))
}

func (UnimplementedAdminServiceHandler) SetQueueConcurrencyLimit(context.Context, *connect.Request[v1.SetQueueConcurrencyLimitRequest]) (*connect.Response[v1.SetQueueConcurrencyLimitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.SetQueueConcurrencyLimit is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteQueueConcurrencyLimit(context.Context, *connect.Request[v1.DeleteQueueConcurrencyLimitRequest]) (*connect.Response[v1.DeleteQueueConcurrencyLimitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.DeleteQueueConcurrencyLimit is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListTasks is not implemented"))
}

func (UnimplementedAdminServiceHandler) CancelTask(context.Context, *connect.Request[v1.CancelTaskRequest]) (*connect.Response[v1.CancelTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.CancelTask is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.DeleteTask is not implemented"))
}

func (UnimplementedAdminServiceHandler) RunTask(context.Context, *connect.Request[v1.RunTaskRequest]) (*connect.Response[v1.RunTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.RunTask is not implemented"))
}

func (UnimplementedAdminServiceHandler) ArchiveTask(context.Context, *connect.Request[v1.ArchiveTaskRequest]) (*connect.Response[v1.ArchiveTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ArchiveTask is not implemented"))
}

func (UnimplementedAdminServiceHandler) BatchDeleteTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.BatchDeleteTasks is not implemented"))
}

func (UnimplementedAdminServiceHandler) BatchRunTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.BatchRunTasks is not implemented"))
}

func (UnimplementedAdminServiceHandler) BatchCancelTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.BatchCancelTasks is not implemented"))
}

func (UnimplementedAdminServiceHandler) BatchArchiveTasks(context.Context, *connect.Request[v1.BatchTasksRequest]) (*connect.Response[v1.BatchTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.BatchArchiveTasks is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListCron(context.Context, *connect.Request[v1.ListCronRequest]) (*connect.Response[v1.ListCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListCron is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpsertCron(context.Context, *connect.Request[v1.UpsertCronRequest]) (*connect.Response[v1.UpsertCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.UpsertCron is not implemented"))
}

func (UnimplementedAdminServiceHandler) PauseCron(context.Context, *connect.Request[v1.PauseCronRequest]) (*connect.Response[v1.PauseCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.PauseCron is not implemented"))
}

func (UnimplementedAdminServiceHandler) ResumeCron(context.Context, *connect.Request[v1.ResumeCronRequest]) (*connect.Response[v1.ResumeCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ResumeCron is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteCron(context.Context, *connect.Request[v1.DeleteCronRequest]) (*connect.Response[v1.DeleteCronResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.DeleteCron is not implemented"))
}

func (UnimplementedAdminServiceHandler) ClusterInfo(context.Context, *connect.Request[v1.ClusterInfoRequest]) (*connect.Response[v1.ClusterInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ClusterInfo is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListWorkerSessions(context.Context, *connect.Request[v1.ListWorkerSessionsRequest]) (*connect.Response[v1.ListWorkerSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.ListWorkerSessions is not implemented"))
}

func (UnimplementedAdminServiceHandler) BrokerInfo(context.Context, *connect.Request[v1.BrokerInfoRequest]) (*connect.Response[v1.BrokerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.BrokerInfo is not implemented"))
}

func (UnimplementedAdminServiceHandler) WatchEvents(context.Context, *connect.Request[v1.WatchEventsRequest], *connect.ServerStream[v1.TaskEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("conveyor.v1.AdminService.WatchEvents is not implemented"))
}
