// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conveyor/v1/messages.proto

package conveyorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskEnqueued tells a queue grain that one new task was committed.
type TaskEnqueued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnqueued) Reset() {
	*x = TaskEnqueued{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnqueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnqueued) ProtoMessage() {}

func (x *TaskEnqueued) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnqueued.ProtoReflect.Descriptor instead.
func (*TaskEnqueued) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEnqueued) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// TasksAvailable tells a queue grain that due work exists (reaper sweep).
type TasksAvailable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// hint is the approximate number of due tasks; informational only.
	Hint          int64 `protobuf:"varint,2,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksAvailable) Reset() {
	*x = TasksAvailable{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksAvailable) ProtoMessage() {}

func (x *TasksAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksAvailable.ProtoReflect.Descriptor instead.
func (*TasksAvailable) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TasksAvailable) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TasksAvailable) GetHint() int64 {
	if x != nil {
		return x.Hint
	}
	return 0
}

// RegisterGateway announces a worker gateway and its capacity to a queue
// grain. Re-sent periodically as a heartbeat to heal grain relocation.
type RegisterGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// gateway_name is the gateway actor name used for TellActor dispatch.
	GatewayName string `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// capacity is the worker's declared concurrency for this queue.
	Capacity      int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGateway) Reset() {
	*x = RegisterGateway{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGateway) ProtoMessage() {}

func (x *RegisterGateway) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGateway.ProtoReflect.Descriptor instead.
func (*RegisterGateway) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterGateway) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RegisterGateway) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *RegisterGateway) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// GatewayCredit grants dispatch credits from a gateway to a queue grain.
type GatewayCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	GatewayName   string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCredit) Reset() {
	*x = GatewayCredit{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCredit) ProtoMessage() {}

func (x *GatewayCredit) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCredit.ProtoReflect.Descriptor instead.
func (*GatewayCredit) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayCredit) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *GatewayCredit) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GatewayCredit) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

// ExecuteTask carries one durably leased task from a queue grain to a
// gateway for dispatch down the worker stream.
type ExecuteTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Task           *TaskEnvelope          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ExecuteTask) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ExecuteTask) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

// TaskCompleted signals a finished execution back to the queue grain. It
// is also the credit refill signal: the named gateway regains one dispatch
// credit, which may start another lease cycle.
type TaskCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	GatewayName   string                 `protobuf:"bytes,4,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleted) Reset() {
	*x = TaskCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleted) ProtoMessage() {}

func (x *TaskCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleted.ProtoReflect.Descriptor instead.
func (*TaskCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TaskCompleted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompleted) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompleted) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

// DrainQueue pauses dispatch for a queue (persisted via the broker).
type DrainQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainQueue) Reset() {
	*x = DrainQueue{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainQueue) ProtoMessage() {}

func (x *DrainQueue) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainQueue.ProtoReflect.Descriptor instead.
func (*DrainQueue) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DrainQueue) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// ResumeQueue resumes dispatch for a paused queue.
type ResumeQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeQueue) Reset() {
	*x = ResumeQueue{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeQueue) ProtoMessage() {}

func (x *ResumeQueue) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeQueue.ProtoReflect.Descriptor instead.
func (*ResumeQueue) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeQueue) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// CancelActive asks the gateway executing a task to send a Cancel frame to
// its worker (grain -> gateway -> worker).
type CancelActive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActive) Reset() {
	*x = CancelActive{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActive) ProtoMessage() {}

func (x *CancelActive) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActive.ProtoReflect.Descriptor instead.
func (*CancelActive) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CancelActive) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// FireCron tells the scheduler singleton that a cron entry is due.
type FireCron struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireCron) Reset() {
	*x = FireCron{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireCron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireCron) ProtoMessage() {}

func (x *FireCron) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireCron.ProtoReflect.Descriptor instead.
func (*FireCron) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FireCron) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

// CronEntriesChanged tells the scheduler singleton to reload cron entries
// from the broker after an Admin API mutation.
type CronEntriesChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronEntriesChanged) Reset() {
	*x = CronEntriesChanged{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEntriesChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEntriesChanged) ProtoMessage() {}

func (x *CronEntriesChanged) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEntriesChanged.ProtoReflect.Descriptor instead.
func (*CronEntriesChanged) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{10}
}

// LeaseCycleCompleted delivers the outcome of an asynchronous lease cycle
// back to the queue grain that initiated it. A failed cycle carries the
// broker error message; the next wake-up retries the cycle.
type LeaseCycleCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tasks          []*TaskEnvelope        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	// error is the broker failure message; empty when the cycle succeeded.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseCycleCompleted) Reset() {
	*x = LeaseCycleCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseCycleCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseCycleCompleted) ProtoMessage() {}

func (x *LeaseCycleCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseCycleCompleted.ProtoReflect.Descriptor instead.
func (*LeaseCycleCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *LeaseCycleCompleted) GetTasks() []*TaskEnvelope {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *LeaseCycleCompleted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseCycleCompleted) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *LeaseCycleCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PromoteTick triggers one scheduled-task promotion pass on the scheduler.
type PromoteTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteTick) Reset() {
	*x = PromoteTick{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteTick) ProtoMessage() {}

func (x *PromoteTick) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteTick.ProtoReflect.Descriptor instead.
func (*PromoteTick) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{12}
}

// ReapTick triggers one maintenance pass on the reaper.
type ReapTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapTick) Reset() {
	*x = ReapTick{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapTick) ProtoMessage() {}

func (x *ReapTick) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapTick.ProtoReflect.Descriptor instead.
func (*ReapTick) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{13}
}

var File_conveyor_v1_messages_proto protoreflect.FileDescriptor

const file_conveyor_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aconveyor/v1/messages.proto\x12\vconveyor.v1\x1a\x16conveyor/v1/task.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\fTaskEnqueued\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\":\n" +
	"\x0eTasksAvailable\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x12\n" +
	"\x04hint\x18\x02 \x01(\x03R\x04hint\"f\n" +
	"\x0fRegisterGateway\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"b\n" +
	"\rGatewayCredit\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\"\x9d\x01\n" +
	"\vExecuteTask\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x19.conveyor.v1.TaskEnvelopeR\x04task\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"{\n" +
	"\rTaskCompleted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\fgateway_name\x18\x04 \x01(\tR\vgatewayName\"\"\n" +
	"\n" +
	"DrainQueue\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"#\n" +
	"\vResumeQueue\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"'\n" +
	"\fCancelActive\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"%\n" +
	"\bFireCron\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"\x14\n" +
	"\x12CronEntriesChanged\"\xbd\x01\n" +
	"\x13LeaseCycleCompleted\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.conveyor.v1.TaskEnvelopeR\x05tasks\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\r\n" +
	"\vPromoteTick\"\n" +
	"\n" +
	"\bReapTickB\xb1\x01\n" +
	"\x0fcom.conveyor.v1B\rMessagesProtoP\x01ZBgithub.com/tochemey/conveyor/internal/proto/conveyor/v1;conveyorv1\xa2\x02\x03CXX\xaa\x02\vConveyor.V1\xca\x02\vConveyor\\V1\xe2\x02\x17Conveyor\\V1\\GPBMetadata\xea\x02\fConveyor::V1b\x06proto3"

var (
	file_conveyor_v1_messages_proto_rawDescOnce sync.Once
	file_conveyor_v1_messages_proto_rawDescData []byte
)

func file_conveyor_v1_messages_proto_rawDescGZIP() []byte {
	file_conveyor_v1_messages_proto_rawDescOnce.Do(func() {
		file_conveyor_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conveyor_v1_messages_proto_rawDesc), len(file_conveyor_v1_messages_proto_rawDesc)))
	})
	return file_conveyor_v1_messages_proto_rawDescData
}

var file_conveyor_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_conveyor_v1_messages_proto_goTypes = []any{
	(*TaskEnqueued)(nil),          // 0: conveyor.v1.TaskEnqueued
	(*TasksAvailable)(nil),        // 1: conveyor.v1.TasksAvailable
	(*RegisterGateway)(nil),       // 2: conveyor.v1.RegisterGateway
	(*GatewayCredit)(nil),         // 3: conveyor.v1.GatewayCredit
	(*ExecuteTask)(nil),           // 4: conveyor.v1.ExecuteTask
	(*TaskCompleted)(nil),         // 5: conveyor.v1.TaskCompleted
	(*DrainQueue)(nil),            // 6: conveyor.v1.DrainQueue
	(*ResumeQueue)(nil),           // 7: conveyor.v1.ResumeQueue
	(*CancelActive)(nil),          // 8: conveyor.v1.CancelActive
	(*FireCron)(nil),              // 9: conveyor.v1.FireCron
	(*CronEntriesChanged)(nil),    // 10: conveyor.v1.CronEntriesChanged
	(*LeaseCycleCompleted)(nil),   // 11: conveyor.v1.LeaseCycleCompleted
	(*PromoteTick)(nil),           // 12: conveyor.v1.PromoteTick
	(*ReapTick)(nil),              // 13: conveyor.v1.ReapTick
	(*TaskEnvelope)(nil),          // 14: conveyor.v1.TaskEnvelope
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_conveyor_v1_messages_proto_depIdxs = []int32{
	14, // 0: conveyor.v1.ExecuteTask.task:type_name -> conveyor.v1.TaskEnvelope
	15, // 1: conveyor.v1.ExecuteTask.lease_expires_at:type_name -> google.protobuf.Timestamp
	14, // 2: conveyor.v1.LeaseCycleCompleted.tasks:type_name -> conveyor.v1.TaskEnvelope
	15, // 3: conveyor.v1.LeaseCycleCompleted.lease_expires_at:type_name -> google.protobuf.Timestamp
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_conveyor_v1_messages_proto_init() }
func file_conveyor_v1_messages_proto_init() {
	if File_conveyor_v1_messages_proto != nil {
		return
	}
	file_conveyor_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conveyor_v1_messages_proto_rawDesc), len(file_conveyor_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conveyor_v1_messages_proto_goTypes,
		DependencyIndexes: file_conveyor_v1_messages_proto_depIdxs,
		MessageInfos:      file_conveyor_v1_messages_proto_msgTypes,
	}.Build()
	File_conveyor_v1_messages_proto = out.File
	file_conveyor_v1_messages_proto_goTypes = nil
	file_conveyor_v1_messages_proto_depIdxs = nil
}
