// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: conveyor/v1/messages.proto

package conveyorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskEnqueued tells a queue grain that one new task was committed.
type TaskEnqueued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnqueued) Reset() {
	*x = TaskEnqueued{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnqueued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnqueued) ProtoMessage() {}

func (x *TaskEnqueued) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnqueued.ProtoReflect.Descriptor instead.
func (*TaskEnqueued) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEnqueued) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// TasksAvailable tells a queue grain that due work exists (reaper sweep).
type TasksAvailable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// hint is the approximate number of due tasks; informational only.
	Hint          int64 `protobuf:"varint,2,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksAvailable) Reset() {
	*x = TasksAvailable{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksAvailable) ProtoMessage() {}

func (x *TasksAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksAvailable.ProtoReflect.Descriptor instead.
func (*TasksAvailable) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TasksAvailable) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TasksAvailable) GetHint() int64 {
	if x != nil {
		return x.Hint
	}
	return 0
}

// RegisterGateway announces a worker gateway and its capacity to a queue
// grain. Re-sent periodically as a heartbeat to heal grain relocation.
type RegisterGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// gateway_name is the gateway actor name used for TellActor dispatch.
	GatewayName string `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// capacity is the worker's declared concurrency for this queue.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// batch_types are the task types this gateway's worker handles as batches,
	// so the grain dispatches a fired group only to a capable gateway.
	BatchTypes []string `protobuf:"bytes,4,rep,name=batch_types,json=batchTypes,proto3" json:"batch_types,omitempty"`
	// weight is the worker's declared dispatch weight for this queue. The grain
	// distributes leased tasks across gateways in proportion to their weights, so
	// a higher weight draws proportionally more work. A non-positive value (an
	// older worker that predates weighted dispatch) is treated as weight one.
	Weight        int32 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGateway) Reset() {
	*x = RegisterGateway{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGateway) ProtoMessage() {}

func (x *RegisterGateway) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGateway.ProtoReflect.Descriptor instead.
func (*RegisterGateway) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterGateway) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RegisterGateway) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *RegisterGateway) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RegisterGateway) GetBatchTypes() []string {
	if x != nil {
		return x.BatchTypes
	}
	return nil
}

func (x *RegisterGateway) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// GatewayCredit grants dispatch credits from a gateway to a queue grain.
type GatewayCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	GatewayName   string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCredit) Reset() {
	*x = GatewayCredit{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCredit) ProtoMessage() {}

func (x *GatewayCredit) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCredit.ProtoReflect.Descriptor instead.
func (*GatewayCredit) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayCredit) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *GatewayCredit) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GatewayCredit) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

// ExecuteTask carries one durably leased task from a queue grain to a
// gateway for dispatch down the worker stream.
type ExecuteTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Task           *TaskEnvelope          `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTask) GetTask() *TaskEnvelope {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ExecuteTask) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ExecuteTask) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

// ExecuteBatch carries one durably leased aggregation group from a queue grain
// to a gateway for batch dispatch. The members share one lease_id; the gateway
// delivers them as a single BatchDispatch frame.
type ExecuteBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tasks          []*TaskEnvelope        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	Group          string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteBatch) Reset() {
	*x = ExecuteBatch{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatch) ProtoMessage() {}

func (x *ExecuteBatch) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatch.ProtoReflect.Descriptor instead.
func (*ExecuteBatch) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteBatch) GetTasks() []*TaskEnvelope {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ExecuteBatch) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ExecuteBatch) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *ExecuteBatch) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// FireGroup tells a queue grain that an aggregation group is due: the grain
// leases its members and batch-dispatches them. The group-sweeper singleton
// sends it after a group's size, delay, or grace threshold trips.
type FireGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Group string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// type is the group's task type (members are single-type), used to pick a
	// batch-capable gateway before leasing.
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireGroup) Reset() {
	*x = FireGroup{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireGroup) ProtoMessage() {}

func (x *FireGroup) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireGroup.ProtoReflect.Descriptor instead.
func (*FireGroup) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *FireGroup) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *FireGroup) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FireGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// GroupLeaseCompleted delivers the outcome of an asynchronous group lease back
// to the queue grain that initiated it. Leasing runs off the grain turn through
// PipeToSelf (broker I/O never blocks the grain), and the grain dispatches the
// batch when this arrives. A failed lease carries the broker error message.
type GroupLeaseCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tasks          []*TaskEnvelope        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	Group          string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	// type is the group's task type, used to re-pick a batch-capable gateway at
	// dispatch time (a gateway may have changed since the lease began).
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// error is the broker failure message; empty when the lease succeeded.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupLeaseCompleted) Reset() {
	*x = GroupLeaseCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupLeaseCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLeaseCompleted) ProtoMessage() {}

func (x *GroupLeaseCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLeaseCompleted.ProtoReflect.Descriptor instead.
func (*GroupLeaseCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GroupLeaseCompleted) GetTasks() []*TaskEnvelope {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *GroupLeaseCompleted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *GroupLeaseCompleted) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *GroupLeaseCompleted) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupLeaseCompleted) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupLeaseCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TaskCompleted signals a finished execution back to the queue grain. It
// is also the credit refill signal: the named gateway regains one dispatch
// credit, which may start another lease cycle.
type TaskCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	GatewayName   string                 `protobuf:"bytes,4,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleted) Reset() {
	*x = TaskCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleted) ProtoMessage() {}

func (x *TaskCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleted.ProtoReflect.Descriptor instead.
func (*TaskCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *TaskCompleted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompleted) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompleted) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

// BatchCompleted signals a finished batch execution back to the queue grain.
// One batch consumes one dispatch credit regardless of member count, so it
// refills exactly one credit; total and succeeded update the task counters.
type BatchCompleted struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Queue       string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	GatewayName string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// total is the number of members in the batch.
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// succeeded is how many members completed successfully.
	Succeeded     int32 `protobuf:"varint,4,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCompleted) Reset() {
	*x = BatchCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCompleted) ProtoMessage() {}

func (x *BatchCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCompleted.ProtoReflect.Descriptor instead.
func (*BatchCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCompleted) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *BatchCompleted) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *BatchCompleted) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchCompleted) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

// DrainQueue pauses dispatch for a queue (persisted via the broker).
type DrainQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainQueue) Reset() {
	*x = DrainQueue{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainQueue) ProtoMessage() {}

func (x *DrainQueue) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainQueue.ProtoReflect.Descriptor instead.
func (*DrainQueue) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DrainQueue) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// ResumeQueue resumes dispatch for a paused queue.
type ResumeQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeQueue) Reset() {
	*x = ResumeQueue{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeQueue) ProtoMessage() {}

func (x *ResumeQueue) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeQueue.ProtoReflect.Descriptor instead.
func (*ResumeQueue) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeQueue) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// CancelActive asks the gateway executing a task to send a Cancel frame to
// its worker (grain -> gateway -> worker).
type CancelActive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelActive) Reset() {
	*x = CancelActive{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelActive) ProtoMessage() {}

func (x *CancelActive) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelActive.ProtoReflect.Descriptor instead.
func (*CancelActive) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *CancelActive) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// RateLimitChanged tells a queue grain that its dispatch-rate override changed
// through the Admin API. It carries the new values so the grain rebuilds its
// token bucket without a broker read: rate_per_sec greater than zero sets the
// override, while zero reverts the queue to the server's global default.
type RateLimitChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	RatePerSec    float64                `protobuf:"fixed64,2,opt,name=rate_per_sec,json=ratePerSec,proto3" json:"rate_per_sec,omitempty"`
	Burst         int32                  `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitChanged) Reset() {
	*x = RateLimitChanged{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitChanged) ProtoMessage() {}

func (x *RateLimitChanged) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitChanged.ProtoReflect.Descriptor instead.
func (*RateLimitChanged) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RateLimitChanged) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RateLimitChanged) GetRatePerSec() float64 {
	if x != nil {
		return x.RatePerSec
	}
	return 0
}

func (x *RateLimitChanged) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

// ConcurrencyLimitChanged tells a queue grain that its per-key concurrency limit
// changed through the Admin API. It carries the new value so the grain updates
// its keyed semaphore without a broker read: max_active greater than zero sets
// the limit, while zero clears it and leaves the queue's keys unbounded.
type ConcurrencyLimitChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	MaxActive     int32                  `protobuf:"varint,2,opt,name=max_active,json=maxActive,proto3" json:"max_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrencyLimitChanged) Reset() {
	*x = ConcurrencyLimitChanged{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencyLimitChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencyLimitChanged) ProtoMessage() {}

func (x *ConcurrencyLimitChanged) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencyLimitChanged.ProtoReflect.Descriptor instead.
func (*ConcurrencyLimitChanged) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ConcurrencyLimitChanged) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ConcurrencyLimitChanged) GetMaxActive() int32 {
	if x != nil {
		return x.MaxActive
	}
	return 0
}

// FireCron tells the scheduler singleton that a cron entry is due.
type FireCron struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireCron) Reset() {
	*x = FireCron{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireCron) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireCron) ProtoMessage() {}

func (x *FireCron) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireCron.ProtoReflect.Descriptor instead.
func (*FireCron) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *FireCron) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

// CronEntriesChanged tells the scheduler singleton to reload cron entries
// from the broker after an Admin API mutation.
type CronEntriesChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronEntriesChanged) Reset() {
	*x = CronEntriesChanged{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronEntriesChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronEntriesChanged) ProtoMessage() {}

func (x *CronEntriesChanged) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronEntriesChanged.ProtoReflect.Descriptor instead.
func (*CronEntriesChanged) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{16}
}

// LeaseCycleCompleted delivers the outcome of an asynchronous lease cycle
// back to the queue grain that initiated it. A failed cycle carries the
// broker error message; the next wake-up retries the cycle.
type LeaseCycleCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tasks          []*TaskEnvelope        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	// error is the broker failure message; empty when the cycle succeeded.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseCycleCompleted) Reset() {
	*x = LeaseCycleCompleted{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseCycleCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseCycleCompleted) ProtoMessage() {}

func (x *LeaseCycleCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseCycleCompleted.ProtoReflect.Descriptor instead.
func (*LeaseCycleCompleted) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *LeaseCycleCompleted) GetTasks() []*TaskEnvelope {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *LeaseCycleCompleted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseCycleCompleted) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *LeaseCycleCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LeasedTasksReleased delivers the outcome of an asynchronous release back
// to the queue grain that initiated it. The grain releases a leased batch
// back to pending when it cannot dispatch it — the queue paused mid-cycle,
// or the only gateways with credits went away — so the work redelivers
// instead of waiting out the lease. The grain only logs this result; the
// counts are informational.
type LeasedTasksReleased struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// released is the number of tasks returned to pending.
	Released int32 `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	// failed is the number whose release failed; those redeliver on lease
	// expiry via the reaper.
	Failed        int32 `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeasedTasksReleased) Reset() {
	*x = LeasedTasksReleased{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasedTasksReleased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasedTasksReleased) ProtoMessage() {}

func (x *LeasedTasksReleased) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasedTasksReleased.ProtoReflect.Descriptor instead.
func (*LeasedTasksReleased) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *LeasedTasksReleased) GetReleased() int32 {
	if x != nil {
		return x.Released
	}
	return 0
}

func (x *LeasedTasksReleased) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

// PromoteTick triggers one scheduled-task promotion pass on the scheduler.
type PromoteTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteTick) Reset() {
	*x = PromoteTick{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteTick) ProtoMessage() {}

func (x *PromoteTick) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteTick.ProtoReflect.Descriptor instead.
func (*PromoteTick) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{19}
}

// ReapTick triggers one maintenance pass on the reaper.
type ReapTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapTick) Reset() {
	*x = ReapTick{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapTick) ProtoMessage() {}

func (x *ReapTick) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapTick.ProtoReflect.Descriptor instead.
func (*ReapTick) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{20}
}

// GroupSweepTick triggers one firing pass on the group-aggregation sweeper.
type GroupSweepTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSweepTick) Reset() {
	*x = GroupSweepTick{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSweepTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSweepTick) ProtoMessage() {}

func (x *GroupSweepTick) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSweepTick.ProtoReflect.Descriptor instead.
func (*GroupSweepTick) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{21}
}

// ResolveDependents asks a dependency resolver to reconcile the tasks waiting on
// one just-finished task and wake any queue whose work became eligible. It is
// dispatched off the gateway's turn so the resolving broker transaction never
// blocks task delivery.
type ResolveDependents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the finished task whose dependents are to be reconciled.
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDependents) Reset() {
	*x = ResolveDependents{}
	mi := &file_conveyor_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDependents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDependents) ProtoMessage() {}

func (x *ResolveDependents) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDependents.ProtoReflect.Descriptor instead.
func (*ResolveDependents) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *ResolveDependents) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_conveyor_v1_messages_proto protoreflect.FileDescriptor

const file_conveyor_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aconveyor/v1/messages.proto\x12\vconveyor.v1\x1a\x16conveyor/v1/task.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\fTaskEnqueued\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\":\n" +
	"\x0eTasksAvailable\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x12\n" +
	"\x04hint\x18\x02 \x01(\x03R\x04hint\"\x9f\x01\n" +
	"\x0fRegisterGateway\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vbatch_types\x18\x04 \x03(\tR\n" +
	"batchTypes\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\"b\n" +
	"\rGatewayCredit\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\"\x9d\x01\n" +
	"\vExecuteTask\x12-\n" +
	"\x04task\x18\x01 \x01(\v2\x19.conveyor.v1.TaskEnvelopeR\x04task\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"\xb6\x01\n" +
	"\fExecuteBatch\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.conveyor.v1.TaskEnvelopeR\x05tasks\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\"K\n" +
	"\tFireGroup\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xe7\x01\n" +
	"\x13GroupLeaseCompleted\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.conveyor.v1.TaskEnvelopeR\x05tasks\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"{\n" +
	"\rTaskCompleted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\fgateway_name\x18\x04 \x01(\tR\vgatewayName\"}\n" +
	"\x0eBatchCompleted\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1c\n" +
	"\tsucceeded\x18\x04 \x01(\x05R\tsucceeded\"\"\n" +
	"\n" +
	"DrainQueue\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"#\n" +
	"\vResumeQueue\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"'\n" +
	"\fCancelActive\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"`\n" +
	"\x10RateLimitChanged\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12 \n" +
	"\frate_per_sec\x18\x02 \x01(\x01R\n" +
	"ratePerSec\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x05R\x05burst\"N\n" +
	"\x17ConcurrencyLimitChanged\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"max_active\x18\x02 \x01(\x05R\tmaxActive\"%\n" +
	"\bFireCron\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"\x14\n" +
	"\x12CronEntriesChanged\"\xbd\x01\n" +
	"\x13LeaseCycleCompleted\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.conveyor.v1.TaskEnvelopeR\x05tasks\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\x13LeasedTasksReleased\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\x05R\breleased\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\"\r\n" +
	"\vPromoteTick\"\n" +
	"\n" +
	"\bReapTick\"\x10\n" +
	"\x0eGroupSweepTick\",\n" +
	"\x11ResolveDependents\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskIdB\xb2\x01\n" +
	"\x0fcom.conveyor.v1B\rMessagesProtoP\x01ZCgithub.com/conveyorq/conveyor/internal/proto/conveyor/v1;conveyorv1\xa2\x02\x03CXX\xaa\x02\vConveyor.V1\xca\x02\vConveyor\\V1\xe2\x02\x17Conveyor\\V1\\GPBMetadata\xea\x02\fConveyor::V1b\x06proto3"

var (
	file_conveyor_v1_messages_proto_rawDescOnce sync.Once
	file_conveyor_v1_messages_proto_rawDescData []byte
)

func file_conveyor_v1_messages_proto_rawDescGZIP() []byte {
	file_conveyor_v1_messages_proto_rawDescOnce.Do(func() {
		file_conveyor_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conveyor_v1_messages_proto_rawDesc), len(file_conveyor_v1_messages_proto_rawDesc)))
	})
	return file_conveyor_v1_messages_proto_rawDescData
}

var file_conveyor_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_conveyor_v1_messages_proto_goTypes = []any{
	(*TaskEnqueued)(nil),            // 0: conveyor.v1.TaskEnqueued
	(*TasksAvailable)(nil),          // 1: conveyor.v1.TasksAvailable
	(*RegisterGateway)(nil),         // 2: conveyor.v1.RegisterGateway
	(*GatewayCredit)(nil),           // 3: conveyor.v1.GatewayCredit
	(*ExecuteTask)(nil),             // 4: conveyor.v1.ExecuteTask
	(*ExecuteBatch)(nil),            // 5: conveyor.v1.ExecuteBatch
	(*FireGroup)(nil),               // 6: conveyor.v1.FireGroup
	(*GroupLeaseCompleted)(nil),     // 7: conveyor.v1.GroupLeaseCompleted
	(*TaskCompleted)(nil),           // 8: conveyor.v1.TaskCompleted
	(*BatchCompleted)(nil),          // 9: conveyor.v1.BatchCompleted
	(*DrainQueue)(nil),              // 10: conveyor.v1.DrainQueue
	(*ResumeQueue)(nil),             // 11: conveyor.v1.ResumeQueue
	(*CancelActive)(nil),            // 12: conveyor.v1.CancelActive
	(*RateLimitChanged)(nil),        // 13: conveyor.v1.RateLimitChanged
	(*ConcurrencyLimitChanged)(nil), // 14: conveyor.v1.ConcurrencyLimitChanged
	(*FireCron)(nil),                // 15: conveyor.v1.FireCron
	(*CronEntriesChanged)(nil),      // 16: conveyor.v1.CronEntriesChanged
	(*LeaseCycleCompleted)(nil),     // 17: conveyor.v1.LeaseCycleCompleted
	(*LeasedTasksReleased)(nil),     // 18: conveyor.v1.LeasedTasksReleased
	(*PromoteTick)(nil),             // 19: conveyor.v1.PromoteTick
	(*ReapTick)(nil),                // 20: conveyor.v1.ReapTick
	(*GroupSweepTick)(nil),          // 21: conveyor.v1.GroupSweepTick
	(*ResolveDependents)(nil),       // 22: conveyor.v1.ResolveDependents
	(*TaskEnvelope)(nil),            // 23: conveyor.v1.TaskEnvelope
	(*timestamppb.Timestamp)(nil),   // 24: google.protobuf.Timestamp
}
var file_conveyor_v1_messages_proto_depIdxs = []int32{
	23, // 0: conveyor.v1.ExecuteTask.task:type_name -> conveyor.v1.TaskEnvelope
	24, // 1: conveyor.v1.ExecuteTask.lease_expires_at:type_name -> google.protobuf.Timestamp
	23, // 2: conveyor.v1.ExecuteBatch.tasks:type_name -> conveyor.v1.TaskEnvelope
	24, // 3: conveyor.v1.ExecuteBatch.lease_expires_at:type_name -> google.protobuf.Timestamp
	23, // 4: conveyor.v1.GroupLeaseCompleted.tasks:type_name -> conveyor.v1.TaskEnvelope
	24, // 5: conveyor.v1.GroupLeaseCompleted.lease_expires_at:type_name -> google.protobuf.Timestamp
	23, // 6: conveyor.v1.LeaseCycleCompleted.tasks:type_name -> conveyor.v1.TaskEnvelope
	24, // 7: conveyor.v1.LeaseCycleCompleted.lease_expires_at:type_name -> google.protobuf.Timestamp
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_conveyor_v1_messages_proto_init() }
func file_conveyor_v1_messages_proto_init() {
	if File_conveyor_v1_messages_proto != nil {
		return
	}
	file_conveyor_v1_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conveyor_v1_messages_proto_rawDesc), len(file_conveyor_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conveyor_v1_messages_proto_goTypes,
		DependencyIndexes: file_conveyor_v1_messages_proto_depIdxs,
		MessageInfos:      file_conveyor_v1_messages_proto_msgTypes,
	}.Build()
	File_conveyor_v1_messages_proto = out.File
	file_conveyor_v1_messages_proto_goTypes = nil
	file_conveyor_v1_messages_proto_depIdxs = nil
}
