// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: conveyor/v1/task.proto

package conveyorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskState enumerates the lifecycle states of a task.
//
// The numeric values are stable and mirror the broker storage encoding;
// they must never be renumbered.
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	// TASK_STATE_SCHEDULED is a task whose process_at lies in the future.
	TaskState_TASK_STATE_SCHEDULED TaskState = 1
	// TASK_STATE_PENDING is a task that is due and waiting for a lease.
	TaskState_TASK_STATE_PENDING TaskState = 2
	// TASK_STATE_ACTIVE is a task currently leased to a worker.
	TaskState_TASK_STATE_ACTIVE TaskState = 3
	// TASK_STATE_RETRY is a failed task waiting for its backoff to elapse.
	TaskState_TASK_STATE_RETRY TaskState = 4
	// TASK_STATE_COMPLETED is a successfully executed task retained until purge.
	TaskState_TASK_STATE_COMPLETED TaskState = 5
	// TASK_STATE_ARCHIVED is a dead-lettered task (retries exhausted or skipped).
	TaskState_TASK_STATE_ARCHIVED TaskState = 6
	// TASK_STATE_CANCELED is a task canceled via the Admin API before completion.
	TaskState_TASK_STATE_CANCELED TaskState = 7
	// TASK_STATE_AGGREGATING is a group member accumulating in the broker until
	// its group fires (by size, delay, or grace period), at which point the
	// group's members are leased together and delivered to a worker as one batch.
	TaskState_TASK_STATE_AGGREGATING TaskState = 8
	// TASK_STATE_BLOCKED is a task held until every task it depends on reaches a
	// terminal success. It is not eligible to lease while blocked; completing the
	// last dependency promotes it to pending (or scheduled, if it is also delayed).
	TaskState_TASK_STATE_BLOCKED TaskState = 9
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SCHEDULED",
		2: "TASK_STATE_PENDING",
		3: "TASK_STATE_ACTIVE",
		4: "TASK_STATE_RETRY",
		5: "TASK_STATE_COMPLETED",
		6: "TASK_STATE_ARCHIVED",
		7: "TASK_STATE_CANCELED",
		8: "TASK_STATE_AGGREGATING",
		9: "TASK_STATE_BLOCKED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_SCHEDULED":   1,
		"TASK_STATE_PENDING":     2,
		"TASK_STATE_ACTIVE":      3,
		"TASK_STATE_RETRY":       4,
		"TASK_STATE_COMPLETED":   5,
		"TASK_STATE_ARCHIVED":    6,
		"TASK_STATE_CANCELED":    7,
		"TASK_STATE_AGGREGATING": 8,
		"TASK_STATE_BLOCKED":     9,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_conveyor_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_conveyor_v1_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{0}
}

// TaskEventType labels a task lifecycle transition emitted on the event stream.
// It is the transition that occurred; the resulting TaskState rides alongside it
// on the TaskEvent, so a watcher can filter on either the action or the state.
type TaskEventType int32

const (
	TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED TaskEventType = 0
	// TASK_EVENT_TYPE_ENQUEUED is a task newly committed and due (or made due
	// again: a promoted scheduled/blocked task that is now runnable).
	TaskEventType_TASK_EVENT_TYPE_ENQUEUED TaskEventType = 1
	// TASK_EVENT_TYPE_SCHEDULED is a task committed with a future process_at.
	TaskEventType_TASK_EVENT_TYPE_SCHEDULED TaskEventType = 2
	// TASK_EVENT_TYPE_LEASED is a task leased to a worker (now active).
	TaskEventType_TASK_EVENT_TYPE_LEASED TaskEventType = 3
	// TASK_EVENT_TYPE_COMPLETED is a task that executed successfully.
	TaskEventType_TASK_EVENT_TYPE_COMPLETED TaskEventType = 4
	// TASK_EVENT_TYPE_RETRIED is a failed attempt scheduled for a later retry.
	TaskEventType_TASK_EVENT_TYPE_RETRIED TaskEventType = 5
	// TASK_EVENT_TYPE_ARCHIVED is a dead-lettered task (retries exhausted, skipped,
	// expired before dispatch, or canceled mid-execution).
	TaskEventType_TASK_EVENT_TYPE_ARCHIVED TaskEventType = 6
	// TASK_EVENT_TYPE_CANCELED is a waiting task canceled via the Admin API or by a
	// failed dependency's cascade-cancel policy.
	TaskEventType_TASK_EVENT_TYPE_CANCELED TaskEventType = 7
	// TASK_EVENT_TYPE_RELEASED is an active task returned to pending without a retry
	// penalty (graceful worker disconnect).
	TaskEventType_TASK_EVENT_TYPE_RELEASED TaskEventType = 8
)

// Enum value maps for TaskEventType.
var (
	TaskEventType_name = map[int32]string{
		0: "TASK_EVENT_TYPE_UNSPECIFIED",
		1: "TASK_EVENT_TYPE_ENQUEUED",
		2: "TASK_EVENT_TYPE_SCHEDULED",
		3: "TASK_EVENT_TYPE_LEASED",
		4: "TASK_EVENT_TYPE_COMPLETED",
		5: "TASK_EVENT_TYPE_RETRIED",
		6: "TASK_EVENT_TYPE_ARCHIVED",
		7: "TASK_EVENT_TYPE_CANCELED",
		8: "TASK_EVENT_TYPE_RELEASED",
	}
	TaskEventType_value = map[string]int32{
		"TASK_EVENT_TYPE_UNSPECIFIED": 0,
		"TASK_EVENT_TYPE_ENQUEUED":    1,
		"TASK_EVENT_TYPE_SCHEDULED":   2,
		"TASK_EVENT_TYPE_LEASED":      3,
		"TASK_EVENT_TYPE_COMPLETED":   4,
		"TASK_EVENT_TYPE_RETRIED":     5,
		"TASK_EVENT_TYPE_ARCHIVED":    6,
		"TASK_EVENT_TYPE_CANCELED":    7,
		"TASK_EVENT_TYPE_RELEASED":    8,
	}
)

func (x TaskEventType) Enum() *TaskEventType {
	p := new(TaskEventType)
	*p = x
	return p
}

func (x TaskEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_conveyor_v1_task_proto_enumTypes[1].Descriptor()
}

func (TaskEventType) Type() protoreflect.EnumType {
	return &file_conveyor_v1_task_proto_enumTypes[1]
}

func (x TaskEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventType.Descriptor instead.
func (TaskEventType) EnumDescriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{1}
}

// DependencyFailurePolicy decides what happens to a dependent task when one of
// the tasks it depends on fails terminally (archived or canceled).
type DependencyFailurePolicy int32

const (
	// DEPENDENCY_FAILURE_POLICY_UNSPECIFIED defaults to BLOCK.
	DependencyFailurePolicy_DEPENDENCY_FAILURE_POLICY_UNSPECIFIED DependencyFailurePolicy = 0
	// DEPENDENCY_FAILURE_POLICY_BLOCK keeps the dependent blocked indefinitely:
	// the dependency never succeeded, so the dependent never becomes eligible.
	DependencyFailurePolicy_DEPENDENCY_FAILURE_POLICY_BLOCK DependencyFailurePolicy = 1
	// DEPENDENCY_FAILURE_POLICY_CASCADE_CANCEL cancels the dependent (and, in
	// turn, its own dependents) when the dependency fails.
	DependencyFailurePolicy_DEPENDENCY_FAILURE_POLICY_CASCADE_CANCEL DependencyFailurePolicy = 2
	// DEPENDENCY_FAILURE_POLICY_CONTINUE treats the failed dependency as
	// satisfied, so the dependent proceeds once its remaining dependencies clear.
	DependencyFailurePolicy_DEPENDENCY_FAILURE_POLICY_CONTINUE DependencyFailurePolicy = 3
)

// Enum value maps for DependencyFailurePolicy.
var (
	DependencyFailurePolicy_name = map[int32]string{
		0: "DEPENDENCY_FAILURE_POLICY_UNSPECIFIED",
		1: "DEPENDENCY_FAILURE_POLICY_BLOCK",
		2: "DEPENDENCY_FAILURE_POLICY_CASCADE_CANCEL",
		3: "DEPENDENCY_FAILURE_POLICY_CONTINUE",
	}
	DependencyFailurePolicy_value = map[string]int32{
		"DEPENDENCY_FAILURE_POLICY_UNSPECIFIED":    0,
		"DEPENDENCY_FAILURE_POLICY_BLOCK":          1,
		"DEPENDENCY_FAILURE_POLICY_CASCADE_CANCEL": 2,
		"DEPENDENCY_FAILURE_POLICY_CONTINUE":       3,
	}
)

func (x DependencyFailurePolicy) Enum() *DependencyFailurePolicy {
	p := new(DependencyFailurePolicy)
	*p = x
	return p
}

func (x DependencyFailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyFailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_conveyor_v1_task_proto_enumTypes[2].Descriptor()
}

func (DependencyFailurePolicy) Type() protoreflect.EnumType {
	return &file_conveyor_v1_task_proto_enumTypes[2]
}

func (x DependencyFailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyFailurePolicy.Descriptor instead.
func (DependencyFailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{2}
}

// RetryStrategy selects how a task's retry backoff delay grows with the attempt.
type RetryStrategy int32

const (
	// RETRY_STRATEGY_UNSPECIFIED uses the server's default strategy.
	RetryStrategy_RETRY_STRATEGY_UNSPECIFIED RetryStrategy = 0
	// RETRY_STRATEGY_EXPONENTIAL doubles the delay ceiling each retry.
	RetryStrategy_RETRY_STRATEGY_EXPONENTIAL RetryStrategy = 1
	// RETRY_STRATEGY_LINEAR grows the delay ceiling linearly with the attempt.
	RetryStrategy_RETRY_STRATEGY_LINEAR RetryStrategy = 2
	// RETRY_STRATEGY_FIXED holds the delay ceiling constant across retries.
	RetryStrategy_RETRY_STRATEGY_FIXED RetryStrategy = 3
)

// Enum value maps for RetryStrategy.
var (
	RetryStrategy_name = map[int32]string{
		0: "RETRY_STRATEGY_UNSPECIFIED",
		1: "RETRY_STRATEGY_EXPONENTIAL",
		2: "RETRY_STRATEGY_LINEAR",
		3: "RETRY_STRATEGY_FIXED",
	}
	RetryStrategy_value = map[string]int32{
		"RETRY_STRATEGY_UNSPECIFIED": 0,
		"RETRY_STRATEGY_EXPONENTIAL": 1,
		"RETRY_STRATEGY_LINEAR":      2,
		"RETRY_STRATEGY_FIXED":       3,
	}
)

func (x RetryStrategy) Enum() *RetryStrategy {
	p := new(RetryStrategy)
	*p = x
	return p
}

func (x RetryStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetryStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_conveyor_v1_task_proto_enumTypes[3].Descriptor()
}

func (RetryStrategy) Type() protoreflect.EnumType {
	return &file_conveyor_v1_task_proto_enumTypes[3]
}

func (x RetryStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetryStrategy.Descriptor instead.
func (RetryStrategy) EnumDescriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{3}
}

// TaskEvent is one task lifecycle transition delivered on the AdminService
// WatchEvents stream and the optional webhook sink. It is a lightweight
// notification: it carries the task's identity and new state, not its payload.
// Delivery is best-effort and non-durable (fire-and-forget, at-least-once to
// connected listeners); a slow watcher's missed events are dropped, never
// buffered without bound.
type TaskEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the task ULID the transition applies to.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue is the task's queue.
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// type is the handler routing key, e.g. "email:welcome".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// state is the task's lifecycle state after the transition.
	State TaskState `protobuf:"varint,4,opt,name=state,proto3,enum=conveyor.v1.TaskState" json:"state,omitempty"`
	// event_type is the transition that occurred.
	EventType TaskEventType `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=conveyor.v1.TaskEventType" json:"event_type,omitempty"`
	// occurred_at is when the transition was recorded, from the server clock.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// attempt is the task's retry count after the transition.
	Attempt int32 `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// last_error is the most recent failure message, set on retried and archived
	// transitions and empty otherwise.
	LastError     string `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_conveyor_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskEvent) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEvent) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *TaskEvent) GetEventType() TaskEventType {
	if x != nil {
		return x.EventType
	}
	return TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED
}

func (x *TaskEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TaskEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskEvent) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// TaskDependency is one edge of a workflow: the enclosing task must wait for the
// referenced task to reach a terminal state before it becomes eligible to run.
type TaskDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the id of the task that must finish first.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// on_failure decides the dependent's fate if this dependency fails terminally.
	OnFailure     DependencyFailurePolicy `protobuf:"varint,2,opt,name=on_failure,json=onFailure,proto3,enum=conveyor.v1.DependencyFailurePolicy" json:"on_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDependency) Reset() {
	*x = TaskDependency{}
	mi := &file_conveyor_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDependency) ProtoMessage() {}

func (x *TaskDependency) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDependency.ProtoReflect.Descriptor instead.
func (*TaskDependency) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskDependency) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskDependency) GetOnFailure() DependencyFailurePolicy {
	if x != nil {
		return x.OnFailure
	}
	return DependencyFailurePolicy_DEPENDENCY_FAILURE_POLICY_UNSPECIFIED
}

// TaskEnvelope is the internal, durable representation of a task.
//
// The payload is opaque bytes plus a content type; user-visible protobuf is
// forbidden by design. The envelope is what brokers persist and what actor
// messages reference.
type TaskEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the task ULID. Client-assignable; Enqueue is idempotent on it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue is the named queue the task belongs to.
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// type is the handler routing key, e.g. "email:welcome".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// payload is opaque; SDK codecs own the encoding.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// content_type describes the payload encoding, e.g. "application/json".
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// metadata carries user tags and trace propagation (e.g. traceparent).
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// options are the execution options captured at enqueue time.
	Options *TaskOptions `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	// retried is the number of times the task has been retried so far.
	Retried int32 `protobuf:"varint,8,opt,name=retried,proto3" json:"retried,omitempty"`
	// last_error is the message of the most recent failure, if any.
	LastError string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// enqueued_at is when the task was first committed to the broker.
	EnqueuedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// started_at is when the most recent execution attempt was leased to a
	// worker. It is an overlay field: brokers stamp it on reads from the
	// authoritative lease timestamp, never persist it inside the payload.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// completed_at is when the task reached its most recent terminal state
	// (completed, archived, or canceled). It is an overlay field, stamped on
	// reads from the authoritative column. Unset while the task is not terminal.
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// progress is the latest completion estimate (0 to 100) the running worker
	// reported. It is an overlay field, stamped on reads from the authoritative
	// column; zero when none was reported.
	Progress uint32 `protobuf:"varint,13,opt,name=progress,proto3" json:"progress,omitempty"`
	// progress_message is the latest human-readable status reported alongside
	// progress. Overlay field; empty when none was reported.
	ProgressMessage string `protobuf:"bytes,14,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_conveyor_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskEnvelope) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEnvelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TaskEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskEnvelope) GetOptions() *TaskOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TaskEnvelope) GetRetried() int32 {
	if x != nil {
		return x.Retried
	}
	return 0
}

func (x *TaskEnvelope) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *TaskEnvelope) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *TaskEnvelope) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskEnvelope) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskEnvelope) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskEnvelope) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

// TaskOptions captures the per-task execution options.
type TaskOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_retry is the number of retries before archiving. Default 25.
	MaxRetry int32 `protobuf:"varint,1,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	// timeout bounds a single execution attempt.
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// deadline is the absolute time after which the task must not run.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// process_at delays execution until the given time.
	ProcessAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=process_at,json=processAt,proto3" json:"process_at,omitempty"`
	// unique_key enforces uniqueness among incomplete tasks.
	UniqueKey string `protobuf:"bytes,5,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	// unique_ttl bounds how long the uniqueness claim is held.
	UniqueTtl *durationpb.Duration `protobuf:"bytes,6,opt,name=unique_ttl,json=uniqueTtl,proto3" json:"unique_ttl,omitempty"`
	// retention keeps the completed task row for inspection before purge.
	Retention *durationpb.Duration `protobuf:"bytes,7,opt,name=retention,proto3" json:"retention,omitempty"`
	// priority orders dispatch within a queue, 0..9. Default 4.
	Priority int32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	// group, when set, makes the task a member of the named aggregation group
	// within its queue. Members accumulate in the aggregating state and are
	// delivered to a worker as one batch when the group fires. A group is
	// single-type: every member shares the task's type.
	Group string `protobuf:"bytes,9,opt,name=group,proto3" json:"group,omitempty"`
	// expires_at is the absolute time after which the task must not be
	// dispatched: a task still waiting (scheduled, pending, or retrying) when
	// this passes is archived instead of run. It is distinct from deadline,
	// which cancels a task already running, and from retention, which purges a
	// task already completed. Unset leaves the task with no expiry. The server
	// resolves the relative EnqueueRequest.expires_in to this absolute time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// depends_on lists the tasks this task waits for. While any dependency has
	// not reached a terminal success the task stays blocked and is not eligible
	// to lease. An empty list (the default) leaves the task immediately eligible.
	// Fan-in is a continuation that depends on every task of a fan-out batch.
	DependsOn []*TaskDependency `protobuf:"bytes,11,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// concurrency_key caps how many tasks sharing it run at once: the queue
	// dispatches at most its configured concurrency limit of tasks with this key
	// simultaneously, holding the rest pending until an active one finishes. Empty
	// (the default) leaves the task unbounded. It is distinct from unique_key,
	// which forbids a duplicate outright. Mutually exclusive with group, which is
	// dispatched as a batch on a separate path.
	ConcurrencyKey string `protobuf:"bytes,12,opt,name=concurrency_key,json=concurrencyKey,proto3" json:"concurrency_key,omitempty"`
	// retry_policy overrides the server's default retry backoff for this task,
	// e.g. a fast linear retry for a flaky internal call or a long fixed delay
	// for a rate-limited downstream. Unset uses the server default.
	RetryPolicy   *RetryPolicy `protobuf:"bytes,13,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOptions) Reset() {
	*x = TaskOptions{}
	mi := &file_conveyor_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOptions) ProtoMessage() {}

func (x *TaskOptions) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOptions.ProtoReflect.Descriptor instead.
func (*TaskOptions) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskOptions) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *TaskOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskOptions) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TaskOptions) GetProcessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessAt
	}
	return nil
}

func (x *TaskOptions) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *TaskOptions) GetUniqueTtl() *durationpb.Duration {
	if x != nil {
		return x.UniqueTtl
	}
	return nil
}

func (x *TaskOptions) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *TaskOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskOptions) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *TaskOptions) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TaskOptions) GetDependsOn() []*TaskDependency {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TaskOptions) GetConcurrencyKey() string {
	if x != nil {
		return x.ConcurrencyKey
	}
	return ""
}

func (x *TaskOptions) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

// RetryPolicy overrides the server's default retry backoff for one task. Each
// field falls back to the server default when left at its zero value, so a task
// can override only the strategy, only the timing, or all of it.
type RetryPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// strategy selects how the backoff delay grows.
	Strategy RetryStrategy `protobuf:"varint,1,opt,name=strategy,proto3,enum=conveyor.v1.RetryStrategy" json:"strategy,omitempty"`
	// base is the first-retry delay ceiling.
	Base *durationpb.Duration `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	// max bounds the delay regardless of how many retries have elapsed.
	Max           *durationpb.Duration `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_conveyor_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *RetryPolicy) GetStrategy() RetryStrategy {
	if x != nil {
		return x.Strategy
	}
	return RetryStrategy_RETRY_STRATEGY_UNSPECIFIED
}

func (x *RetryPolicy) GetBase() *durationpb.Duration {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RetryPolicy) GetMax() *durationpb.Duration {
	if x != nil {
		return x.Max
	}
	return nil
}

var File_conveyor_v1_task_proto protoreflect.FileDescriptor

const file_conveyor_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x16conveyor/v1/task.proto\x12\vconveyor.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\tTaskEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.conveyor.v1.TaskStateR\x05state\x129\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x1a.conveyor.v1.TaskEventTypeR\teventType\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\"n\n" +
	"\x0eTaskDependency\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12C\n" +
	"\n" +
	"on_failure\x18\x02 \x01(\x0e2$.conveyor.v1.DependencyFailurePolicyR\tonFailure\"\xf2\x04\n" +
	"\fTaskEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.conveyor.v1.TaskEnvelope.MetadataEntryR\bmetadata\x122\n" +
	"\aoptions\x18\a \x01(\v2\x18.conveyor.v1.TaskOptionsR\aoptions\x12\x18\n" +
	"\aretried\x18\b \x01(\x05R\aretried\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12;\n" +
	"\venqueued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1a\n" +
	"\bprogress\x18\r \x01(\rR\bprogress\x12)\n" +
	"\x10progress_message\x18\x0e \x01(\tR\x0fprogressMessage\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x04\n" +
	"\vTaskOptions\x12\x1b\n" +
	"\tmax_retry\x18\x01 \x01(\x05R\bmaxRetry\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x129\n" +
	"\n" +
	"process_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tprocessAt\x12\x1d\n" +
	"\n" +
	"unique_key\x18\x05 \x01(\tR\tuniqueKey\x128\n" +
	"\n" +
	"unique_ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\tuniqueTtl\x127\n" +
	"\tretention\x18\a \x01(\v2\x19.google.protobuf.DurationR\tretention\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x14\n" +
	"\x05group\x18\t \x01(\tR\x05group\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\n" +
	"depends_on\x18\v \x03(\v2\x1b.conveyor.v1.TaskDependencyR\tdependsOn\x12'\n" +
	"\x0fconcurrency_key\x18\f \x01(\tR\x0econcurrencyKey\x12;\n" +
	"\fretry_policy\x18\r \x01(\v2\x18.conveyor.v1.RetryPolicyR\vretryPolicyJ\x04\b\x0e\x10\x10\"\xa1\x01\n" +
	"\vRetryPolicy\x126\n" +
	"\bstrategy\x18\x01 \x01(\x0e2\x1a.conveyor.v1.RetryStrategyR\bstrategy\x12-\n" +
	"\x04base\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04base\x12+\n" +
	"\x03max\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03max*\x86\x02\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SCHEDULED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x02\x12\x15\n" +
	"\x11TASK_STATE_ACTIVE\x10\x03\x12\x14\n" +
	"\x10TASK_STATE_RETRY\x10\x04\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x05\x12\x17\n" +
	"\x13TASK_STATE_ARCHIVED\x10\x06\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\a\x12\x1a\n" +
	"\x16TASK_STATE_AGGREGATING\x10\b\x12\x16\n" +
	"\x12TASK_STATE_BLOCKED\x10\t*\x9f\x02\n" +
	"\rTaskEventType\x12\x1f\n" +
	"\x1bTASK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TASK_EVENT_TYPE_ENQUEUED\x10\x01\x12\x1d\n" +
	"\x19TASK_EVENT_TYPE_SCHEDULED\x10\x02\x12\x1a\n" +
	"\x16TASK_EVENT_TYPE_LEASED\x10\x03\x12\x1d\n" +
	"\x19TASK_EVENT_TYPE_COMPLETED\x10\x04\x12\x1b\n" +
	"\x17TASK_EVENT_TYPE_RETRIED\x10\x05\x12\x1c\n" +
	"\x18TASK_EVENT_TYPE_ARCHIVED\x10\x06\x12\x1c\n" +
	"\x18TASK_EVENT_TYPE_CANCELED\x10\a\x12\x1c\n" +
	"\x18TASK_EVENT_TYPE_RELEASED\x10\b*\xbf\x01\n" +
	"\x17DependencyFailurePolicy\x12)\n" +
	"%DEPENDENCY_FAILURE_POLICY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDEPENDENCY_FAILURE_POLICY_BLOCK\x10\x01\x12,\n" +
	"(DEPENDENCY_FAILURE_POLICY_CASCADE_CANCEL\x10\x02\x12&\n" +
	"\"DEPENDENCY_FAILURE_POLICY_CONTINUE\x10\x03*\x84\x01\n" +
	"\rRetryStrategy\x12\x1e\n" +
	"\x1aRETRY_STRATEGY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRETRY_STRATEGY_EXPONENTIAL\x10\x01\x12\x19\n" +
	"\x15RETRY_STRATEGY_LINEAR\x10\x02\x12\x18\n" +
	"\x14RETRY_STRATEGY_FIXED\x10\x03B\xae\x01\n" +
	"\x0fcom.conveyor.v1B\tTaskProtoP\x01ZCgithub.com/conveyorq/conveyor/internal/proto/conveyor/v1;conveyorv1\xa2\x02\x03CXX\xaa\x02\vConveyor.V1\xca\x02\vConveyor\\V1\xe2\x02\x17Conveyor\\V1\\GPBMetadata\xea\x02\fConveyor::V1b\x06proto3"

var (
	file_conveyor_v1_task_proto_rawDescOnce sync.Once
	file_conveyor_v1_task_proto_rawDescData []byte
)

func file_conveyor_v1_task_proto_rawDescGZIP() []byte {
	file_conveyor_v1_task_proto_rawDescOnce.Do(func() {
		file_conveyor_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conveyor_v1_task_proto_rawDesc), len(file_conveyor_v1_task_proto_rawDesc)))
	})
	return file_conveyor_v1_task_proto_rawDescData
}

var file_conveyor_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_conveyor_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_conveyor_v1_task_proto_goTypes = []any{
	(TaskState)(0),                // 0: conveyor.v1.TaskState
	(TaskEventType)(0),            // 1: conveyor.v1.TaskEventType
	(DependencyFailurePolicy)(0),  // 2: conveyor.v1.DependencyFailurePolicy
	(RetryStrategy)(0),            // 3: conveyor.v1.RetryStrategy
	(*TaskEvent)(nil),             // 4: conveyor.v1.TaskEvent
	(*TaskDependency)(nil),        // 5: conveyor.v1.TaskDependency
	(*TaskEnvelope)(nil),          // 6: conveyor.v1.TaskEnvelope
	(*TaskOptions)(nil),           // 7: conveyor.v1.TaskOptions
	(*RetryPolicy)(nil),           // 8: conveyor.v1.RetryPolicy
	nil,                           // 9: conveyor.v1.TaskEnvelope.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
}
var file_conveyor_v1_task_proto_depIdxs = []int32{
	0,  // 0: conveyor.v1.TaskEvent.state:type_name -> conveyor.v1.TaskState
	1,  // 1: conveyor.v1.TaskEvent.event_type:type_name -> conveyor.v1.TaskEventType
	10, // 2: conveyor.v1.TaskEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 3: conveyor.v1.TaskDependency.on_failure:type_name -> conveyor.v1.DependencyFailurePolicy
	9,  // 4: conveyor.v1.TaskEnvelope.metadata:type_name -> conveyor.v1.TaskEnvelope.MetadataEntry
	7,  // 5: conveyor.v1.TaskEnvelope.options:type_name -> conveyor.v1.TaskOptions
	10, // 6: conveyor.v1.TaskEnvelope.enqueued_at:type_name -> google.protobuf.Timestamp
	10, // 7: conveyor.v1.TaskEnvelope.started_at:type_name -> google.protobuf.Timestamp
	10, // 8: conveyor.v1.TaskEnvelope.completed_at:type_name -> google.protobuf.Timestamp
	11, // 9: conveyor.v1.TaskOptions.timeout:type_name -> google.protobuf.Duration
	10, // 10: conveyor.v1.TaskOptions.deadline:type_name -> google.protobuf.Timestamp
	10, // 11: conveyor.v1.TaskOptions.process_at:type_name -> google.protobuf.Timestamp
	11, // 12: conveyor.v1.TaskOptions.unique_ttl:type_name -> google.protobuf.Duration
	11, // 13: conveyor.v1.TaskOptions.retention:type_name -> google.protobuf.Duration
	10, // 14: conveyor.v1.TaskOptions.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 15: conveyor.v1.TaskOptions.depends_on:type_name -> conveyor.v1.TaskDependency
	8,  // 16: conveyor.v1.TaskOptions.retry_policy:type_name -> conveyor.v1.RetryPolicy
	3,  // 17: conveyor.v1.RetryPolicy.strategy:type_name -> conveyor.v1.RetryStrategy
	11, // 18: conveyor.v1.RetryPolicy.base:type_name -> google.protobuf.Duration
	11, // 19: conveyor.v1.RetryPolicy.max:type_name -> google.protobuf.Duration
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_conveyor_v1_task_proto_init() }
func file_conveyor_v1_task_proto_init() {
	if File_conveyor_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conveyor_v1_task_proto_rawDesc), len(file_conveyor_v1_task_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conveyor_v1_task_proto_goTypes,
		DependencyIndexes: file_conveyor_v1_task_proto_depIdxs,
		EnumInfos:         file_conveyor_v1_task_proto_enumTypes,
		MessageInfos:      file_conveyor_v1_task_proto_msgTypes,
	}.Build()
	File_conveyor_v1_task_proto = out.File
	file_conveyor_v1_task_proto_goTypes = nil
	file_conveyor_v1_task_proto_depIdxs = nil
}
