// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conveyor/v1/task.proto

package conveyorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskState enumerates the lifecycle states of a task.
//
// The numeric values are stable and mirror the broker storage encoding;
// they must never be renumbered.
type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	// TASK_STATE_SCHEDULED is a task whose process_at lies in the future.
	TaskState_TASK_STATE_SCHEDULED TaskState = 1
	// TASK_STATE_PENDING is a task that is due and waiting for a lease.
	TaskState_TASK_STATE_PENDING TaskState = 2
	// TASK_STATE_ACTIVE is a task currently leased to a worker.
	TaskState_TASK_STATE_ACTIVE TaskState = 3
	// TASK_STATE_RETRY is a failed task waiting for its backoff to elapse.
	TaskState_TASK_STATE_RETRY TaskState = 4
	// TASK_STATE_COMPLETED is a successfully executed task retained until purge.
	TaskState_TASK_STATE_COMPLETED TaskState = 5
	// TASK_STATE_ARCHIVED is a dead-lettered task (retries exhausted or skipped).
	TaskState_TASK_STATE_ARCHIVED TaskState = 6
	// TASK_STATE_CANCELED is a task canceled via the Admin API before completion.
	TaskState_TASK_STATE_CANCELED TaskState = 7
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_SCHEDULED",
		2: "TASK_STATE_PENDING",
		3: "TASK_STATE_ACTIVE",
		4: "TASK_STATE_RETRY",
		5: "TASK_STATE_COMPLETED",
		6: "TASK_STATE_ARCHIVED",
		7: "TASK_STATE_CANCELED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_SCHEDULED":   1,
		"TASK_STATE_PENDING":     2,
		"TASK_STATE_ACTIVE":      3,
		"TASK_STATE_RETRY":       4,
		"TASK_STATE_COMPLETED":   5,
		"TASK_STATE_ARCHIVED":    6,
		"TASK_STATE_CANCELED":    7,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_conveyor_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_conveyor_v1_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{0}
}

// TaskEnvelope is the internal, durable representation of a task.
//
// The payload is opaque bytes plus a content type; user-visible protobuf is
// forbidden by design. The envelope is what brokers persist and what actor
// messages reference.
type TaskEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the task ULID. Client-assignable; Enqueue is idempotent on it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// queue is the named queue the task belongs to.
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	// type is the handler routing key, e.g. "email:welcome".
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// payload is opaque; SDK codecs own the encoding.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// content_type describes the payload encoding, e.g. "application/json".
	ContentType string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// metadata carries user tags and trace propagation (e.g. traceparent).
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// options are the execution options captured at enqueue time.
	Options *TaskOptions `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	// retried is the number of times the task has been retried so far.
	Retried int32 `protobuf:"varint,8,opt,name=retried,proto3" json:"retried,omitempty"`
	// last_error is the message of the most recent failure, if any.
	LastError string `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// enqueued_at is when the task was first committed to the broker.
	EnqueuedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// started_at is when the most recent execution attempt was leased to a
	// worker. It is an overlay field: brokers stamp it on reads from the
	// authoritative lease timestamp, never persist it inside the payload.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// completed_at is when the task reached its most recent terminal state
	// (completed, archived, or canceled). It is an overlay field, stamped on
	// reads from the authoritative column. Unset while the task is not terminal.
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_conveyor_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskEnvelope) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEnvelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TaskEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskEnvelope) GetOptions() *TaskOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TaskEnvelope) GetRetried() int32 {
	if x != nil {
		return x.Retried
	}
	return 0
}

func (x *TaskEnvelope) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *TaskEnvelope) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *TaskEnvelope) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskEnvelope) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// TaskOptions captures the per-task execution options.
type TaskOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_retry is the number of retries before archiving. Default 25.
	MaxRetry int32 `protobuf:"varint,1,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	// timeout bounds a single execution attempt.
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// deadline is the absolute time after which the task must not run.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// process_at delays execution until the given time.
	ProcessAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=process_at,json=processAt,proto3" json:"process_at,omitempty"`
	// unique_key enforces uniqueness among incomplete tasks.
	UniqueKey string `protobuf:"bytes,5,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	// unique_ttl bounds how long the uniqueness claim is held.
	UniqueTtl *durationpb.Duration `protobuf:"bytes,6,opt,name=unique_ttl,json=uniqueTtl,proto3" json:"unique_ttl,omitempty"`
	// retention keeps the completed task row for inspection before purge.
	Retention *durationpb.Duration `protobuf:"bytes,7,opt,name=retention,proto3" json:"retention,omitempty"`
	// priority orders dispatch within a queue, 0..9. Default 4.
	Priority      int32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOptions) Reset() {
	*x = TaskOptions{}
	mi := &file_conveyor_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOptions) ProtoMessage() {}

func (x *TaskOptions) ProtoReflect() protoreflect.Message {
	mi := &file_conveyor_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOptions.ProtoReflect.Descriptor instead.
func (*TaskOptions) Descriptor() ([]byte, []int) {
	return file_conveyor_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskOptions) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *TaskOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskOptions) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TaskOptions) GetProcessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessAt
	}
	return nil
}

func (x *TaskOptions) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *TaskOptions) GetUniqueTtl() *durationpb.Duration {
	if x != nil {
		return x.UniqueTtl
	}
	return nil
}

func (x *TaskOptions) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *TaskOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_conveyor_v1_task_proto protoreflect.FileDescriptor

const file_conveyor_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x16conveyor/v1/task.proto\x12\vconveyor.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x04\n" +
	"\fTaskEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.conveyor.v1.TaskEnvelope.MetadataEntryR\bmetadata\x122\n" +
	"\aoptions\x18\a \x01(\v2\x18.conveyor.v1.TaskOptionsR\aoptions\x12\x18\n" +
	"\aretried\x18\b \x01(\x05R\aretried\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12;\n" +
	"\venqueued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x03\n" +
	"\vTaskOptions\x12\x1b\n" +
	"\tmax_retry\x18\x01 \x01(\x05R\bmaxRetry\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x129\n" +
	"\n" +
	"process_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tprocessAt\x12\x1d\n" +
	"\n" +
	"unique_key\x18\x05 \x01(\tR\tuniqueKey\x128\n" +
	"\n" +
	"unique_ttl\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\tuniqueTtl\x127\n" +
	"\tretention\x18\a \x01(\v2\x19.google.protobuf.DurationR\tretention\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriorityJ\x04\b\t\x10\x10*\xd2\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATE_SCHEDULED\x10\x01\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x02\x12\x15\n" +
	"\x11TASK_STATE_ACTIVE\x10\x03\x12\x14\n" +
	"\x10TASK_STATE_RETRY\x10\x04\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x05\x12\x17\n" +
	"\x13TASK_STATE_ARCHIVED\x10\x06\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\aB\xae\x01\n" +
	"\x0fcom.conveyor.v1B\tTaskProtoP\x01ZCgithub.com/conveyorq/conveyor/internal/proto/conveyor/v1;conveyorv1\xa2\x02\x03CXX\xaa\x02\vConveyor.V1\xca\x02\vConveyor\\V1\xe2\x02\x17Conveyor\\V1\\GPBMetadata\xea\x02\fConveyor::V1b\x06proto3"

var (
	file_conveyor_v1_task_proto_rawDescOnce sync.Once
	file_conveyor_v1_task_proto_rawDescData []byte
)

func file_conveyor_v1_task_proto_rawDescGZIP() []byte {
	file_conveyor_v1_task_proto_rawDescOnce.Do(func() {
		file_conveyor_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conveyor_v1_task_proto_rawDesc), len(file_conveyor_v1_task_proto_rawDesc)))
	})
	return file_conveyor_v1_task_proto_rawDescData
}

var file_conveyor_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conveyor_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_conveyor_v1_task_proto_goTypes = []any{
	(TaskState)(0),                // 0: conveyor.v1.TaskState
	(*TaskEnvelope)(nil),          // 1: conveyor.v1.TaskEnvelope
	(*TaskOptions)(nil),           // 2: conveyor.v1.TaskOptions
	nil,                           // 3: conveyor.v1.TaskEnvelope.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
}
var file_conveyor_v1_task_proto_depIdxs = []int32{
	3,  // 0: conveyor.v1.TaskEnvelope.metadata:type_name -> conveyor.v1.TaskEnvelope.MetadataEntry
	2,  // 1: conveyor.v1.TaskEnvelope.options:type_name -> conveyor.v1.TaskOptions
	4,  // 2: conveyor.v1.TaskEnvelope.enqueued_at:type_name -> google.protobuf.Timestamp
	4,  // 3: conveyor.v1.TaskEnvelope.started_at:type_name -> google.protobuf.Timestamp
	4,  // 4: conveyor.v1.TaskEnvelope.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 5: conveyor.v1.TaskOptions.timeout:type_name -> google.protobuf.Duration
	4,  // 6: conveyor.v1.TaskOptions.deadline:type_name -> google.protobuf.Timestamp
	4,  // 7: conveyor.v1.TaskOptions.process_at:type_name -> google.protobuf.Timestamp
	5,  // 8: conveyor.v1.TaskOptions.unique_ttl:type_name -> google.protobuf.Duration
	5,  // 9: conveyor.v1.TaskOptions.retention:type_name -> google.protobuf.Duration
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_conveyor_v1_task_proto_init() }
func file_conveyor_v1_task_proto_init() {
	if File_conveyor_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conveyor_v1_task_proto_rawDesc), len(file_conveyor_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conveyor_v1_task_proto_goTypes,
		DependencyIndexes: file_conveyor_v1_task_proto_depIdxs,
		EnumInfos:         file_conveyor_v1_task_proto_enumTypes,
		MessageInfos:      file_conveyor_v1_task_proto_msgTypes,
	}.Build()
	File_conveyor_v1_task_proto = out.File
	file_conveyor_v1_task_proto_goTypes = nil
	file_conveyor_v1_task_proto_depIdxs = nil
}
